/* DL2 pre-test and post-test item bank (v1, Sept 2026). Item N on each form checks the same
 * skill, domain and week with a different real-life scenario. Answers are balanced A–D (5 each). */
(function (global) {
  'use strict';
  var domains = [
    { id: 'tb', name: 'Technology Basics' }, { id: 'dc', name: 'Digital Citizenship' },
    { id: 'im', name: 'Information Management' }, { id: 'cc', name: 'Content Creation' },
    { id: 'com', name: 'Communication' }, { id: 'col', name: 'Collaboration' }, { id: 'ss', name: 'Safety & Security' }
  ];
  var S = {
    1: 'Make text bigger in every app', 2: 'Fix a page that spills onto a second sheet', 3: 'Fix a repeating calendar event',
    4: 'Write a help request that can be answered', 5: 'Narrow a web search', 6: 'Judge whether a source fits',
    7: 'Act on a wrong confirmation', 8: 'Share with the right permissions', 9: 'Use real heading styles',
    10: 'Check that a SUM total updates', 11: 'Use a licensed photo properly', 12: 'Share a file that looks the same everywhere',
    13: 'Write a clear request with a deadline', 14: 'Know what Bcc does', 15: 'Use respectful, inclusive wording',
    16: 'Give and answer feedback on one shared copy', 17: 'Spot a recurring charge', 18: "Don't rely on color alone",
    19: 'Secure a new account', 20: 'Check a suspicious contact a safer way'
  };
  var W = { 1: 1, 2: 1, 3: 1, 4: 1, 5: 2, 6: 2, 7: 2, 8: 2, 9: 3, 10: 3, 11: 3, 12: 3, 13: 4, 14: 4, 15: 4, 16: 4, 17: 4, 18: 5, 19: 5, 20: 5 };
  var D = { 1: 'tb', 2: 'tb', 3: 'tb', 4: 'com', 5: 'im', 6: 'im', 7: 'im', 8: 'col', 9: 'cc', 10: 'cc', 11: 'dc', 12: 'cc', 13: 'com', 14: 'com', 15: 'dc', 16: 'col', 17: 'ss', 18: 'dc', 19: 'ss', 20: 'ss' };
  function it(n, stem, options, answer, why) { return { n: n, week: W[n], domain: D[n], skill: S[n], stem: stem, options: options, answer: answer, why: why }; }

  var pre = [
    it(1, 'Text is too small in every app you use. Zooming in the web browser only fixed one website. What should you change?',
      ['Zoom in the web browser again', 'The Scale setting in Settings ▸ System ▸ Display', 'The screen resolution, to its lowest setting', 'Nothing. Text size can’t be changed.'], 'B',
      'Display Scale changes text size in every app. Browser zoom only changes web pages.'),
    it(2, 'In print preview, your one-page flyer shows a second page with only the last line on it. What should you do first?',
      ['Print it anyway and throw away page 2', 'Delete the last line of the flyer', 'Make the margins a little smaller, then check the preview again', 'Switch to a different printer'], 'C',
      'Adjusting the layout and re-checking the preview fixes the spill without losing words or paper.'),
    it(3, 'Your weekly Monday class reminder keeps showing up on Tuesdays. What is the best fix?',
      ['Open the event, edit the whole series to repeat weekly on Monday, then check next week', 'Change only this week’s reminder', 'Delete it and try to remember instead', 'Turn off all reminders'], 'A',
      'Editing the series fixes every future reminder; checking the next one proves it worked.'),
    it(4, 'Word shows an error every time you try to save. Which help request will get you the fastest useful answer?',
      ['“Word is broken. Help!”', '“Can someone fix my computer tomorrow?”', '“My computer hates me.”', '“Word (Microsoft 365, Version 2408): when I click Save I see ‘Document not saved.’ I restarted Word and tried Save As. Same message.”'], 'D',
      'Naming the app and version, the task, what you tried and the exact message lets a helper act right away.'),
    it(5, 'You searched for “classes” and got millions of results. You want a beginner computer class near Beckley, WV. Which search is best?',
      ['beginner computer classes Beckley WV, then add a filter such as a date range', 'classes', 'computer', 'free stuff near me'], 'A',
      'Specific words plus a place narrow the results; one filter narrows them further.'),
    it(6, 'A website says its $499 course is “the only way” to pass a computer skills test. What should you do?',
      ['Trust it because the website looks professional', 'Notice the seller profits from that claim, and compare other sources such as the library or a college', 'Buy it now before the price goes up', 'Share it with friends first'], 'B',
      'A source that profits from a claim has a reason to exaggerate, so compare it with independent sources.'),
    it(7, 'After you sign up for a workshop online, the confirmation page shows the wrong date. What should you do?',
      ['Nothing. The confirmation is probably wrong.', 'Submit the form five more times', 'Use the correction or contact method on the confirmation, and keep a copy of it', 'Close the page and forget it'], 'C',
      'The confirmation is your record of what they received, so use their stated way to fix it and keep proof.'),
    it(8, 'You are sharing a budget sheet. One person should fix mistakes; three others only need to look. Which permissions fit?',
      ['Everyone gets Editor', 'Everyone gets Viewer, including the person fixing mistakes', 'Post the link publicly', 'The person fixing mistakes gets Editor; the other three get Viewer'], 'D',
      'Give each person only the access their job needs: Editor to change, Viewer to look.'),
    it(9, 'You made your section titles big and bold, but they don’t appear in Word’s Navigation pane. What should you do?',
      ['Apply real heading styles (Heading 1, Heading 2) from the Home tab', 'Make the titles even bigger', 'Underline the titles', 'Type the titles in all capital letters'], 'A',
      'Word builds navigation and tables of contents from heading styles, not from big bold text.'),
    it(10, 'Cell B7 contains =SUM(B2:B6) and shows 28. You change B3 from 12 to 15. What should B7 show now?',
      ['28', '31', '15', 'An error'], 'B',
      'SUM recalculates: 28 − 12 + 15 = 31. If it didn’t change, the cells aren’t in the range.'),
    it(11, 'A photo’s license says you may crop it if you credit the photographer. How do you use it on your flyer?',
      ['Crop it and leave off the credit', 'Use it with no credit, uncropped', 'Crop a copy and include the photographer’s credit', 'Find the same photo on another site so you don’t need credit'], 'C',
      'Follow the license: cropping is allowed, and the credit is required.'),
    it(12, 'You made a handout in Word for neighbors who may not have Word. How should you share it?',
      ['Send the Word file and hope it opens', 'Take a photo of your screen', 'Copy the text into a text message', 'Save it as a PDF, open the PDF to check it, then share it'], 'D',
      'A PDF looks the same on any device; opening it first catches problems before others see them.'),
    it(13, 'Which email is the clearest request?',
      ['“Please review the attached flyer and reply with any changes by Thursday at noon.”', '“Hey, can you look at this sometime?”', '“FYI.”', '“Here is the flyer.”'], 'A',
      'A clear request says what to do, with what, and by when.'),
    it(14, 'You email 30 veterans about a meeting and put their addresses in Bcc. What does Bcc do?',
      ['Stops anyone from forwarding the email', 'Hides each person’s address from the others', 'Encrypts the email', 'Deletes the email after it’s read'], 'B',
      'Bcc keeps addresses private from the group. It does not stop forwarding or protect the message.'),
    it(15, 'A flyer says: “Older folks probably can’t use video calls, so we’ll call them instead.” What’s the best rewrite?',
      ['Leave it as is. It’s helpful.', '“Video only.”', '“Join by video call, or ask us for a phone call instead.”', '“Young people only.”'], 'C',
      'Offer choices to everyone instead of assuming what a group can or can’t do.'),
    it(16, 'Two people need to suggest edits to the same document, but they can’t work at the same time. What works best?',
      ['Email copies back and forth', 'Everyone makes their own copy', 'Print it and mail it', 'Add comments on one shared draft'], 'D',
      'Comments on one shared copy keep every suggestion in one place, in order.'),
    it(17, 'An app says: “Free for 7 days, then $8/month.” What does this mean?',
      ['After 7 days you’ll be charged $8 every month until you cancel', 'It’s free forever', 'You’ll pay $8 one time', 'You’ll pay only if you like it'], 'A',
      'A trial that turns into a monthly price is a recurring charge. Note the date to cancel if you don’t want it.'),
    it(18, 'A class sign-in sheet shows who is done using only red and green dots. Some people can’t tell red from green. What’s the best fix?',
      ['Make the dots bigger', 'Use a brighter red', 'Add words such as “Complete” and “Not yet” next to the dots', 'Remove the dots and all color'], 'C',
      'Words next to the color make the meaning clear to everyone.'),
    it(19, 'You are creating a new account for a volunteer website. What is the best security choice?',
      ['Reuse your email password so you won’t forget it', 'Use a new, long password you use nowhere else, and turn on two-step verification (MFA)', 'Use “password123”', 'Write your password on a sticky note on the monitor'], 'B',
      'A unique long password plus MFA protects the account even if another site is breached.'),
    it(20, 'A caller says they’re from the VA and need your Social Security number to “keep your benefits.” What should you do?',
      ['Give it. They said they’re from the VA.', 'Call back the number they gave you', 'Text them the number instead', 'Hang up, then call the VA yourself using a number from VA.gov or your VA card'], 'D',
      'Contact the organization through a number you already trust, not one the caller gives you.')
  ];

  var post = [
    it(1, 'A friend says the words in File Explorer, Word and Settings are all hard to read. What is the best single change?',
      ['Turn on Night light', 'Change the desktop background to a darker picture', 'Set Scale in Settings ▸ System ▸ Display to a larger size, such as 125%', 'Zoom in each app one at a time'], 'C',
      'One Display Scale change enlarges text in every app at once.'),
    it(2, 'Before printing 20 copies of a sign-up sheet, what should you do?',
      ['Check print preview, fix anything that spills, then print one test copy', 'Print all 20 and check the first one', 'Make the font tiny so it surely fits', 'Email it to the printer'], 'A',
      'Preview first and test one copy, so a mistake costs one sheet instead of twenty.'),
    it(3, 'You set a repeating reminder to take your medicine at 8:00 AM, but it pops up at 8:00 PM. What should you do?',
      ['Edit only today’s reminder', 'Make a second reminder and keep both', 'Silence the computer at night', 'Edit the whole series to 8:00 AM, then check the next reminder'], 'D',
      'Fix the series so every future reminder is right, then confirm with the next one.'),
    it(4, 'You need to ask the help desk about a printing problem. Which details matter most?',
      ['Your password, so they can log in and check', 'The app and version, what you were doing, what you already tried, and the exact message', 'Just “Printer doesn’t work.” They’ll figure it out.', 'The model number of your monitor'], 'B',
      'Those four details let a helper reproduce the problem. Never share your password.'),
    it(5, 'You want a food pantry that is open on Saturdays in Summers County, WV. Which search is best?',
      ['food', 'pantry recipes', 'Saturday', 'food pantry open Saturday Summers County WV'], 'D',
      'Name the thing, the time and the place to get results that fit.'),
    it(6, 'You find a page listing free tax help, but it was last updated three years ago. What should you do?',
      ['Use it. Tax help never changes.', 'Print it and go without calling', 'Check a current official source or call to confirm the program still runs this year', 'Assume all free tax help is fake'], 'C',
      'Old information may be out of date, so confirm it with a current source before you rely on it.'),
    it(7, 'A confirmation email for your appointment shows the wrong location. What is the best next step?',
      ['Use the change or contact option in the confirmation, give your confirmation number and the right location, and save their reply', 'Reply “wrong” and nothing else', 'Show up at both locations', 'Book a second appointment without canceling the first'], 'A',
      'Use the official route with your confirmation number, and keep the reply as proof.'),
    it(8, 'You want a friend to suggest changes to your résumé without changing it directly. Which permission fits best?',
      ['Editor', 'Commenter', 'Owner', 'Anyone with the link can edit'], 'B',
      'Commenter lets someone suggest without changing your document.'),
    it(9, 'You want Word to build a table of contents from your section titles. What must the titles use?',
      ['Bold text', 'A different font color', 'Font size 20', 'Heading styles, such as Heading 1 and Heading 2'], 'D',
      'Tables of contents and navigation come from heading styles.'),
    it(10, 'Your grocery total uses =SUM(C2:C5) and shows $40. You change one item from $6 to $10. What should the total show?',
      ['$44', '$40', '$10', '$46'], 'A',
      'The total goes up by the $4 difference: $40 + $4 = $44.'),
    it(11, 'You find a great photo online but can’t find any license or permission. What is the safest choice?',
      ['Use it. If it’s online, it’s free.', 'Choose a photo with a clear license and follow its credit rules', 'Use it and write “Found on Google”', 'Take a screenshot so it becomes yours'], 'B',
      'No license means no permission. Use a photo whose license you can follow.'),
    it(12, 'A form must look exactly the same when anyone prints it. Which file should you send?',
      ['A Word document so people can change it', 'A plain text file', 'A PDF, after opening it once to check it', 'A screenshot pasted into an email'], 'C',
      'PDFs keep their layout everywhere; check it before sending.'),
    it(13, 'You need three volunteers to say whether they can help at Saturday’s event. Which subject line and first line work best?',
      ['Subject: “Hi” — “Just checking in.”', 'Subject: “Event” — “See attached.”', 'No subject — “Let me know.”', 'Subject: “Reply by Wed: Can you help Sat 9–11?” — “Please reply yes or no by Wednesday at 5 PM.”'], 'D',
      'Put the request and the deadline where people see them first.'),
    it(14, 'Why use Bcc when writing to a big group who don’t know each other?',
      ['So everyone’s email address stays private from the rest of the group', 'So nobody can reply', 'So the email arrives faster', 'So the message can’t be forwarded'], 'A',
      'Bcc protects the group’s addresses. It doesn’t stop replies or forwarding.'),
    it(15, 'A class announcement says “Guys, bring your laptops.” What is a more welcoming version?',
      ['“Guys and gals, bring laptops.”', '“Everyone, please bring a laptop if you have one. We have loaners too.”', '“Only people with laptops should come.”', 'Leave it the same.'], 'B',
      'Address everyone and remove barriers, such as offering loaner laptops.'),
    it(16, 'A reviewer comments: “Add the help desk phone number after step 3.” What is the best response?',
      ['Delete the comment', 'Reply “OK” and change nothing', 'Add the verified number after step 3, reply “Added,” and resolve the comment', 'Add any phone number you can find quickly'], 'C',
      'Make the change with accurate information, then answer and close the comment so everyone knows.'),
    it(17, 'Before you tap “Start free trial,” what should you check?',
      ['The app’s colors', 'How many stars it has, and nothing else', 'Nothing. Trials are always free.', 'When the trial ends, what it will cost, how often, and how to cancel'], 'D',
      'Know the end date, the price, how often you’ll pay, and how to cancel before you agree.'),
    it(18, 'A chart uses only color to show “on time” and “late.” How do you make it readable for everyone?',
      ['Add labels or patterns so it doesn’t depend on color alone', 'Use even more colors', 'Make it smaller', 'Turn it black and white with no labels'], 'A',
      'Labels or patterns carry the meaning for people who can’t see the colors.'),
    it(19, 'A website asks you to create a password. Which choice is strongest?',
      ['Your pet’s name', 'The same password you use for email', 'A long passphrase you use nowhere else, such as “Maple-River-Tractor-42!”, plus two-step verification', '12345678'], 'C',
      'Long, unique and backed by MFA is the strongest combination.'),
    it(20, 'An email says your bank account is locked and gives a link to “unlock it now.” What is the safest move?',
      ['Click the link quickly', 'Don’t click. Open your bank’s app or call the number on your card to check.', 'Reply with your account number', 'Forward it to friends, then click'], 'B',
      'Go to the bank through a route you already trust, never through the message’s link.')
  ];

  var api = { version: 'v1-2026-09', domains: domains, pre: pre, post: post };
  if (typeof module === 'object' && module.exports) module.exports = api; else global.DL2Items = api;
})(typeof window !== 'undefined' ? window : globalThis);
