/* DL2 pre-test and post-test item bank (v1, Sept 2026). Item N on each form checks the same
 * skill, domain and week with a different real-life scenario. Answers are balanced A–D (5 each).
 * Length never gives the answer away: distractors are real, specific mistakes about as long as the key. */
(function (global) {
  'use strict';
  var domains = [
    { id: 'tb', name: 'Technology Basics' }, { id: 'dc', name: 'Digital Citizenship' },
    { id: 'im', name: 'Information Management' }, { id: 'cc', name: 'Content Creation' },
    { id: 'com', name: 'Communication' }, { id: 'col', name: 'Collaboration' }, { id: 'ss', name: 'Safety & Security' }
  ];
  var S = {
    1: 'Make text bigger in every app', 2: 'Fix a page that spills onto a second sheet', 3: 'Fix a repeating calendar event',
    4: 'Write a help request that can be answered', 5: 'Narrow a web search', 6: 'Judge whether a source fits',
    7: 'Act on a wrong confirmation', 8: 'Share with the right permissions', 9: 'Use real heading styles',
    10: 'Check that a SUM total updates', 11: 'Use a licensed photo properly', 12: 'Share a file that looks the same everywhere',
    13: 'Write a clear request with a deadline', 14: 'Know what Bcc does', 15: 'Use respectful, inclusive wording',
    16: 'Give and answer feedback on one shared copy', 17: 'Spot a recurring charge', 18: "Don't rely on color alone",
    19: 'Secure a new account', 20: 'Check a suspicious contact a safer way'
  };
  var W = { 1: 1, 2: 1, 3: 1, 4: 1, 5: 2, 6: 2, 7: 2, 8: 2, 9: 3, 10: 3, 11: 3, 12: 3, 13: 4, 14: 4, 15: 4, 16: 4, 17: 4, 18: 5, 19: 5, 20: 5 };
  var D = { 1: 'tb', 2: 'tb', 3: 'tb', 4: 'com', 5: 'im', 6: 'im', 7: 'im', 8: 'col', 9: 'cc', 10: 'cc', 11: 'dc', 12: 'cc', 13: 'com', 14: 'com', 15: 'dc', 16: 'col', 17: 'ss', 18: 'dc', 19: 'ss', 20: 'ss' };
  function it(n, stem, options, answer, why) { return { n: n, week: W[n], domain: D[n], skill: S[n], stem: stem, options: options, answer: answer, why: why }; }

  var pre = [
    it(1, 'Text is too small in every app you use. Zooming in the web browser only fixed one website. What should you change?',
      ['Zoom in the web browser again, a little more each time', 'The Scale setting in Settings ▸ System ▸ Display', 'The mouse pointer size in Accessibility settings', 'The font size in each document, one document at a time'], 'B',
      'Display Scale changes text size in every app. Browser zoom only changes web pages.'),
    it(2, 'In print preview, your one-page flyer shows a second page with only the last line on it. What should you do first?',
      ['Print it anyway, then throw away the second page', 'Delete the last line of text so the flyer fits on one page', 'Make the margins a little smaller, then check the preview again', 'Switch to a different printer, then print a copy to see if it fits'], 'C',
      'Adjusting the layout and re-checking the preview fixes the spill without losing words or paper.'),
    it(3, 'Your weekly Monday class reminder keeps showing up on Tuesdays. What is the best fix?',
      ['Edit the whole series to repeat on Monday, then check next week', 'Move only this week’s reminder to Monday, then check that it moved', 'Make a new Monday reminder, and keep the old Tuesday one as well', 'Delete the reminder and write the class on a paper calendar'], 'A',
      'Editing the series fixes every future reminder; checking the next one proves it worked.'),
    it(4, 'Word shows an error every time you try to save. Which help request will get you the fastest useful answer?',
      ['“Word is broken again. I’ve tried everything and nothing works. Please help me soon!”', '“Can someone come fix my computer tomorrow? It keeps showing an error and I have a deadline.”', '“I need help with Word. My password is Blue42 if you want to log in and look around.”', '“Word, Version 2408: when I click Save, I see ‘Document not saved.’ I restarted Word and tried Save As.”'], 'D',
      'Naming the app and version, the task, what you tried and the exact message lets a helper act right away.'),
    it(5, 'You searched for “classes” and got millions of results. You want a beginner computer class near Beckley, WV. Which search is best?',
      ['beginner computer classes Beckley WV, then add a date filter', 'classes, then scroll the results until one looks right', 'computer, then click the first ad at the top of the results', 'beginner classes, then add a date filter and a price filter'], 'A',
      'Specific words plus a place narrow the results; one filter narrows them further.'),
    it(6, 'A website says its $499 course is “the only way” to pass a computer skills test. What should you do?',
      ['Trust it, because the website looks professional and has many five-star reviews', 'Notice that the seller profits from the claim, and compare other sources', 'Buy it today, before the sale price goes up, so you don’t miss the chance', 'Ask the website’s own chat helper whether the course really is the only way'], 'B',
      'A source that profits from a claim has a reason to exaggerate, so compare it with independent sources.'),
    it(7, 'After you sign up for a workshop online, the confirmation page shows the wrong date. What should you do?',
      ['Ignore it, since the confirmation page is probably wrong and they have the right date', 'Fill out the sign-up form again with the right date, and keep both sign-ups', 'Use the correction or contact method on the confirmation, and keep a copy', 'Close the page and show up on the date you meant to choose'], 'C',
      'The confirmation is your record of what they received, so use their stated way to fix it and keep proof.'),
    it(8, 'You are sharing a budget sheet. One person should fix mistakes; three others only need to look. Which permissions fit?',
      ['Everyone gets Editor, so nobody has to ask you for access later', 'Everyone gets Viewer, including the person fixing mistakes', 'Share it as “Anyone with the link can edit” so it’s quick for everyone', 'The person fixing mistakes gets Editor; the other three get Viewer'], 'D',
      'Give each person only the access their job needs: Editor to change, Viewer to look.'),
    it(9, 'You made your section titles big and bold, but they don’t appear in Word’s Navigation pane. What should you do?',
      ['Apply heading styles, such as Heading 1, from the Home tab', 'Make the titles bigger still, such as 24 point, from the Home tab', 'Underline the titles and give them a different color', 'Type the titles in all capital letters so they stand out more'], 'A',
      'Word builds navigation and tables of contents from heading styles, not from big bold text.'),
    it(10, 'Cell B7 contains =SUM(B2:B6) and shows 28. You change B3 from 12 to 15. What should B7 show now?',
      ['28', '31', '15', 'An error'], 'B',
      'SUM recalculates: 28 − 12 + 15 = 31. If it didn’t change, the cells aren’t in the range.'),
    it(11, 'A photo’s license says you may crop it if you credit the photographer. How do you use it on your flyer?',
      ['Crop it and leave off the credit', 'Use it with no credit, uncropped', 'Crop a copy and include the photographer’s credit', 'Find the same photo on another site so you don’t need credit'], 'C',
      'Follow the license: cropping is allowed, and the credit is required.'),
    it(12, 'You made a handout in Word for neighbors who may not have Word. How should you share it?',
      ['Send the Word file, since most people can open it with something', 'Take a photo of your screen with your phone and send the picture', 'Copy the text into a text message, and leave out the pictures', 'Save it as a PDF, open the PDF to check it, then share it'], 'D',
      'A PDF looks the same on any device; opening it first catches problems before others see them.'),
    it(13, 'Which email is the clearest request?',
      ['“Please review the flyer and reply with any changes by Thursday at noon.”', '“Hey, when you get a chance sometime, could you maybe take a look at this for me?”', '“Here is the flyer I told you about. Let me know what you think, whenever you can.”', '“FYI, I attached the flyer for the event, in case you want to see it.”'], 'A',
      'A clear request says what to do, with what, and by when.'),
    it(14, 'You email 30 veterans about a meeting and put their addresses in Bcc. What does Bcc do?',
      ['Stops anyone from forwarding the email to people outside the group', 'Hides each person’s address from the others', 'Locks the email so only the 30 people on the list can open it', 'Deletes the email from everyone’s inbox after it has been read'], 'B',
      'Bcc keeps addresses private from the group. It does not stop forwarding or protect the message.'),
    it(15, 'A flyer says: “Older folks probably can’t use video calls, so we’ll call them instead.” What’s the best rewrite?',
      ['Leave it as is, since it’s meant to be helpful', '“Everyone must join by video call. Ask a grandchild to help.”', '“Join by video call, or ask us for a phone call instead.”', '“Older folks will get a phone call. Everyone else, use video.”'], 'C',
      'Offer choices to everyone instead of assuming what a group can or can’t do.'),
    it(16, 'Two people need to suggest edits to the same document, but they can’t work at the same time. What works best?',
      ['Email copies back and forth, and add the date to each file name', 'Each person edits their own copy, and you combine them at the end', 'Print it, mark it up by hand, and mail it to the next person', 'Both add comments on one shared draft, whenever they can'], 'D',
      'Comments on one shared copy keep every suggestion in one place, in order.'),
    it(17, 'An app says: “Free for 7 days, then $8/month.” What does this mean?',
      ['After 7 days, you pay $8 every month until you cancel', 'It stays free as long as you only use the basic features', 'After 7 days, you pay $8 one time, and then it’s yours to keep', 'You pay $8 at the end of the trial only if you decide you like it'], 'A',
      'A trial that turns into a monthly price is a recurring charge. Note the date to cancel if you don’t want it.'),
    it(18, 'A class sign-in sheet shows who is done using only red and green dots. Some people can’t tell red from green. What’s the best fix?',
      ['Make the dots bigger so the colors are easier to see', 'Use a brighter red and a darker green so they stand apart', 'Add words such as “Complete” and “Not yet” next to the dots', 'Remove the dots and all color, so nobody is confused'], 'C',
      'Words next to the color make the meaning clear to everyone.'),
    it(19, 'You are creating a new account for a volunteer website. What is the best security choice?',
      ['Reuse your email password, since it’s already long and hard to guess', 'Use a long password you use nowhere else, and turn on two-step verification', 'Use a short password with a number in it, such as “Tiger7,” so it’s easy to type', 'Use a long password, and write it on a sticky note on the monitor'], 'B',
      'A unique long password plus two-step verification (MFA) protects the account even if another site is breached.'),
    it(20, 'A caller says they’re from the VA and need your Social Security number to “keep your benefits.” What should you do?',
      ['Give it, since they said they’re from the VA and knew your name', 'Hang up, then call back the number the caller gave you to check', 'Ask them to text you a link, then send the number that way', 'Hang up, then call the VA using a number from VA.gov or your VA card'], 'D',
      'Contact the organization through a number you already trust, not one the caller gives you.')
  ];

  var post = [
    it(1, 'A friend says the words in File Explorer, Word and Settings are all hard to read. What is the best single change?',
      ['Turn on Night light in Settings ▸ System ▸ Display', 'Change the desktop background to a darker, plainer picture', 'Set Scale in Settings ▸ System ▸ Display to a larger size', 'Zoom in inside each of the three apps, one at a time'], 'C',
      'One Display Scale change enlarges text in every app at once.'),
    it(2, 'Before printing 20 copies of a sign-up sheet, what should you do?',
      ['Check print preview, fix any spill, then print one test copy', 'Print all 20 copies, then check the first one for mistakes', 'Make the font as small as it goes so it surely fits on one page', 'Save it as a PDF, then send all 20 copies to the printer'], 'A',
      'Preview first and test one copy, so a mistake costs one sheet instead of twenty.'),
    it(3, 'You set a repeating reminder to take your medicine at 8:00 AM, but it pops up at 8:00 PM. What should you do?',
      ['Change only today’s reminder to 8:00 AM, then check that it moved', 'Make a second reminder for 8:00 AM and keep the 8:00 PM one too', 'Turn off the computer’s sound at night so the reminder stays quiet', 'Edit the whole series to 8:00 AM, then check the next reminder'], 'D',
      'Fix the series so every future reminder is right, then confirm with the next one.'),
    it(4, 'You need to ask the help desk about a printing problem. Which details matter most?',
      ['Your password, so they can log in to your computer and check it themselves', 'The app and version, what you were doing, what you tried, and the exact message', 'How upset you are, how long it has been broken, and how soon you need it working again', 'Your computer’s serial number and the date you bought the printer'], 'B',
      'Those four details let a helper reproduce the problem. Never share your password.'),
    it(5, 'You want a food pantry that is open on Saturdays in Summers County, WV. Which search is best?',
      ['food, then scroll until you find a pantry', 'pantry recipes for Saturday in Summers County WV', 'food pantry, then click the first ad you see', 'food pantry open Saturday Summers County WV'], 'D',
      'Name the thing, the time and the place to get results that fit.'),
    it(6, 'You find a page listing free tax help, but it was last updated three years ago. What should you do?',
      ['Use it as it is, since free tax help programs stay the same every year', 'Print the page and drive to the address on it, without calling first', 'Call or check a current official source to confirm it still runs this year', 'Skip free tax help, because an old page means the program must be a scam'], 'C',
      'Old information may be out of date, so confirm it with a current source before you rely on it.'),
    it(7, 'A confirmation email for your appointment shows the wrong location. What is the best next step?',
      ['Use the confirmation’s change or contact option, give your confirmation number, and save the reply', 'Reply to the email with just the word “wrong,” then wait to see if anyone answers', 'Show up at both locations that day, just in case one of them is right', 'Book a second appointment at the right location, and keep the first one just in case'], 'A',
      'Use the official route with your confirmation number, and keep the reply as proof.'),
    it(8, 'You want a friend to suggest changes to your résumé without changing it directly. Which permission fits best?',
      ['Editor', 'Commenter', 'Owner', 'Anyone with the link can edit'], 'B',
      'Commenter lets someone suggest without changing your document.'),
    it(9, 'You want Word to build a table of contents from your section titles. What must the titles use?',
      ['Bold text, so Word can tell that they are titles', 'A different font color from the rest of the text', 'A bigger font size, such as 20 point', 'Heading styles, such as Heading 1 and Heading 2'], 'D',
      'Tables of contents and navigation come from heading styles.'),
    it(10, 'Your grocery total uses =SUM(C2:C5) and shows $40. You change one item from $6 to $10. What should the total show?',
      ['$44', '$40', '$10', '$46'], 'A',
      'The total goes up by the $4 difference: $40 + $4 = $44.'),
    it(11, 'You find a great photo online but can’t find any license or permission. What is the safest choice?',
      ['Use it, since anything that shows up in a web search is free to use', 'Choose a photo with a clear license and follow its credit rules', 'Use it and write “Found on Google” under it as the credit', 'Take a screenshot of it, so the copy on your computer belongs to you'], 'B',
      'No license means no permission. Use a photo whose license you can follow.'),
    it(12, 'A form must look exactly the same when anyone prints it. Which file should you send?',
      ['A Word document, so people can change it if they need to', 'A plain text file, since every computer can open one', 'A PDF, after opening it once to check it', 'A screenshot of the form pasted into an email'], 'C',
      'PDFs keep their layout everywhere; check it before sending.'),
    it(13, 'You need three volunteers to say whether they can help at Saturday’s event. Which subject line and first line work best?',
      ['Subject: “Hi there” — “Just checking in to see how everyone is doing.”', 'Subject: “Saturday event” — “See the attached file for all the details.”', 'No subject — “Let me know when you get a chance if you might be able to help.”', 'Subject: “Reply by Wed: Can you help Sat 9–11?” — “Please reply yes or no by Wednesday.”'], 'D',
      'Put the request and the deadline where people see them first.'),
    it(14, 'Why use Bcc when writing to a big group who don’t know each other?',
      ['So everyone’s address stays private from the rest of the group', 'So nobody can reply to the email, not even to you, the sender', 'So the email arrives faster, since it skips the other addresses', 'So the message can’t be forwarded to anyone outside the group'], 'A',
      'Bcc protects the group’s addresses. It doesn’t stop replies or forwarding.'),
    it(15, 'A class announcement says “Guys, bring your laptops.” What is a more welcoming version?',
      ['“Guys and gals, please remember to bring your laptops to class this week.”', '“Everyone, please bring a laptop if you have one. We have loaners.”', '“Only people who own their own laptop should come to this class.”', 'Leave it the same, since “guys” just means everyone'], 'B',
      'Address everyone and remove barriers, such as offering loaner laptops.'),
    it(16, 'A reviewer comments: “Add the help desk phone number after step 3.” What is the best response?',
      ['Delete the comment so the document looks clean before anyone else sees it', 'Reply “OK, will do” and resolve the comment, then fix it later if you remember', 'Add the verified number after step 3, reply “Added,” and resolve the comment', 'Add the first phone number you find online, reply “Added,” and resolve it'], 'C',
      'Make the change with accurate information, then answer and close the comment so everyone knows.'),
    it(17, 'Before you tap “Start free trial,” what should you check?',
      ['How the app looks, and whether its pictures in the store look nice', 'How many stars it has in the app store and how many people downloaded it', 'Nothing, since you can’t be charged during a free trial', 'When the trial ends, what it costs, how often, and how to cancel'], 'D',
      'Know the end date, the price, how often you’ll pay, and how to cancel before you agree.'),
    it(18, 'A chart uses only color to show “on time” and “late.” How do you make it readable for everyone?',
      ['Add labels or patterns so it doesn’t depend on color alone', 'Use brighter colors for “on time” and “late” so they stand out more', 'Make the chart bigger so the two colors are easier to tell apart', 'Print it in black and white so the colors don’t matter'], 'A',
      'Labels or patterns carry the meaning for people who can’t see the colors.'),
    it(19, 'A website asks you to create a password. Which choice is strongest?',
      ['Your pet’s name with your birth year added to the end', 'The same long password you already use for your email', 'A long passphrase you use nowhere else, plus two-step verification', 'A common word with symbols swapped in for letters, such as “P@ssw0rd!”'], 'C',
      'Long, unique and backed by two-step verification (MFA) is the strongest combination.'),
    it(20, 'An email says your bank account is locked and gives a link to “unlock it now.” What is the safest move?',
      ['Click the link, but only sign in if the page looks real', 'Don’t click. Open your bank’s app or call the number on your card.', 'Reply to the email and ask whether it’s real before you act', 'Call the phone number listed in the email to check if it’s real'], 'B',
      'Go to the bank through a route you already trust, never through the message’s link.')
  ];

  var api = { version: 'v1-2026-09', domains: domains, pre: pre, post: post };
  if (typeof module === 'object' && module.exports) module.exports = api; else global.DL2Items = api;
})(typeof window !== 'undefined' ? window : globalThis);
