import json
from pathlib import Path
# Each scene has a teaching point, a concise visual and original narration.
V=[
('Make one change and test it',[
 ('Start with the task',['Read a page','Hear the sound','Keep the change'],"A useful computer setup begins with the task you want to do. Suppose the words on a webpage are hard to read. Decide which control affects that page, make one change, and check the result before changing anything else."),
 ('Choose the right control',['Webpage: browser zoom','Desktop: display scaling'],"Browser zoom makes a webpage larger or smaller. Display scaling affects the wider desktop. If only the webpage is difficult to read, try browser zoom first. Use the text size controls when they are available, and check that buttons and instructions remain usable."),
 ('Check the actual output',['Select the speaker','Check mute and volume','Play a short test'],"When sound is missing, first check the selected output device and mute setting. A connected headset may be receiving the sound. Adjust the volume, then play a short test. The same habit applies to printing: choose the printer and inspect a test page."),
 ('Share only what is needed',['Calendar: free or busy','Details: only when needed'],"A practice calendar entry needs a title, a start and end, a location, and a useful reminder. If a partner only needs your availability, look for free or busy sharing. Check the actual options instead of assuming every service shares the same details."),
 ('Try and explain',['Make one adjustment','Show the result','Restore shared settings'],"Pause here and make one helpful adjustment on your workstation. Show a partner what changed and explain how to undo it. Before leaving a shared computer, restore the lab settings and save your practice work. You now have a repeatable routine: choose, test, and explain.")]),
('Cloud files: share and recover',[
 ('Know where the file lives',['This device','Cloud account'],"A file on this computer may not be available on another computer. A cloud service stores a copy under an account. Before switching devices, check that the latest changes have finished saving or syncing, and confirm which account owns or controls the file."),
 ('Permission follows the task',['Viewer: read','Commenter: suggest','Editor: change'],"Choose the smallest permission that lets the other person do the task. A viewer reads. A commenter can suggest wording when the service supports comments. An editor can change the content. Check the recipient carefully, then ask them to verify that the file opens."),
 ('Sync is not a separate backup',['A change can sync','A deletion can sync','Keep a recovery plan'],"Sync carries changes between a device and an online service. It may also carry a deletion. That is why sync alone is not a separate backup. A backup is another recovery copy, and version history may help you recover earlier content when the service supports it."),
 ('Match the recovery tool',['Deleted file: recycle bin','Changed content: version history'],"If the whole file was deleted, check the trash or recycle bin. If the file is still there but its content changed, inspect version history. Preview the earlier version before restoring it, and coordinate with collaborators so you do not overwrite work they need."),
 ('Make a careful practice share',['Fictional file','Named recipient','Limited access'],"Your classmate should suggest clearer wording without rewriting your handout directly. Which permission fits? Pause and decide. Commenter access fits when it is available. Try that choice in the course simulator, explain your reason, and keep all practice records fictional.")]),
('Create, check, and export',[
 ('Start with the reader',['One audience','One useful action'],"A useful handout begins with a reader and a task. Imagine a neighbor who wants computer help. Put the service and next action near the beginning. Leave out details that do not help the person decide what to do, and explain unfamiliar terms."),
 ('Give the document structure',['Heading styles','Short steps','Meaningful links'],"Use real heading styles for sections, a short numbered list for steps, and link text that explains the destination. Making a line bold can change its appearance without creating a heading. Check that the structure still makes sense when you read the document in order."),
 ('Check a small calculation',['Paper: 12','Folders: 8','Pens: 5','Total: 25'],"In a practice workbook, enter paper at twelve dollars, folders at eight, and pens at five. The total is twenty-five. Use a sum formula over all three cells. Change paper to fifteen and check that the total becomes twenty-eight. This tests the formula rather than its appearance."),
 ('Choose the output for the job',['Editable file: revise','PDF: finished layout','CSV: plain table data'],"The right file format depends on the next person's task. An editable document supports revision. A PDF often preserves a finished layout. A CSV carries plain table data but loses formatting and formulas. Choose deliberately, then reopen the exported file and check what survived."),
 ('Show your evidence',['Correct total','Readable structure','Tested export'],"Create a small resource pack: a structured handout, a checked workbook, and three clear slides. Credit any reused material according to its license. Show a partner the calculation and the exported handout. Ask them to find the next action without your help, then improve anything unclear.")]),
('Collaborate without confusion',[
 ('Agree on the task',['Owner','Writer','Reviewer'],"A shared file works better when people know their roles. Choose an owner who makes final decisions, a writer who drafts, and a reviewer who gives feedback. Agree on where the common copy lives and what finished means before several people begin editing."),
 ('Choose when to work',['Together: synchronous','Different times: asynchronous'],"Working on the same document during a live call is synchronous collaboration. Leaving comments for someone to read later is asynchronous collaboration. Choose based on schedules and the decision needed. For later feedback, include enough context that the writer can act without another meeting."),
 ('Make feedback specific',['Name the location','Suggest a change','Explain the reason'],"Helpful feedback names a change and its purpose. You might write: add the contact number after the steps so readers can find help. The writer can accept the idea, ask a question, or explain a different choice. A comment about the work is more useful than a judgment about the person."),
 ('Respect the meeting',['Test sound','Mute when needed','Ask before recording'],"Before a meeting, test the sound and choose the correct microphone. Mute when appropriate, use the agreed chat or raise-hand tools, and ask before recording. In a webinar, the host may control who can speak. Follow the event's instructions and respect other participants."),
 ('Leave a clear next step',['Who does what?','When is it needed?','How will we check?'],"Draft a fictional message asking a partner to review your handout. Use a specific subject, one clear request, and a reasonable response time. Choose feedback access when that fits. After the review, record the decision and verify the final file. No real message needs to be sent for this practice.")]),
('Pause, verify, and protect',[
 ('Pressure is a reason to pause',['Unexpected urgency','Requests for secrets','Unfamiliar links'],"An unexpected message says you must act immediately to keep a service. Urgency can push you to skip checks. Pause before opening the link or providing information. Find the organization through a known website or contact method, then verify the claim independently."),
 ('Permission needs a purpose',['Camera for a meeting','No camera for simple text'],"A video meeting may need camera access. A simple text page usually does not. Grant permissions only when they fit a clear task and you trust the app. You can deny an unrelated request and review camera or microphone permissions after you finish."),
 ('Protect the device and file',['Unknown USB: do not connect','Encryption: key required','Read-only: editing restricted'],"Do not plug in an unknown USB drive to discover who owns it. Give it to authorized staff. Encryption makes data unreadable without a key. Read-only settings restrict editing, which is a different protection. A locked or encrypted device still needs careful account and file access."),
 ('Protect your attention too',['False identity: catfishing','Fear of missing out: FOMO','Take a screen break'],"Online safety also includes attention and wellbeing. Catfishing uses a false identity to build trust. Fear of missing out can make it hard to stop checking alerts. Set useful notification limits, take breaks, and seek support when online behavior makes you feel pressured or unsafe."),
 ('Explain a safe next step',['What is the evidence?','Who can verify it?','What action limits risk?'],"Choose one practice scenario and explain your next step to a partner. Name the evidence, the independent source you would check, and the action that limits risk. Then complete the skills challenge and post-test. Use the results to choose a task for more practice.")]),
('Build a small app: prompt and test',[
 ('Define one useful task',['Find a fictional resource','Search and filter','Explain empty results'],"Start with a small problem: help someone find a fictional community resource. Keep the first app to one page with search, a category filter, and readable results. Write three checks before asking AI to build anything, so you can tell whether the result actually works."),
 ('Understand the parts',['HTML: structure','CSS: appearance','JavaScript: behavior'],"HTML gives the page its content and structure. CSS controls appearance and layout. JavaScript responds to input, such as filtering a list. The supplied starter keeps fictional records inside the file. It has no real account system, private database, or payment service."),
 ('Give a bounded prompt',['Describe the user task','Require keyboard access','Exclude private data'],"Tell the AI what the user should do, which controls are needed, and how to test them. Ask for labeled fields, visible keyboard focus, and no external dependencies. Use fictional data. Do not place passwords or private API keys in browser code, because people can inspect that code."),
 ('Test before you trust',['Matching search','No matching result','Keyboard and small screen'],"Run the checks yourself. Try a matching name, a search with no results, and different letter cases. Use only the keyboard, then narrow the screen. Record what you expected and what actually happened. A confident AI statement does not count as evidence that these paths work."),
 ('Revise, then check again',['Save version 1','Make one change','Repeat the tests'],"Save a first version, request or make one small improvement, and repeat the affected test. Also repeat a test that already passed to catch a new problem. If no AI tool is available, edit the starter's heading and a fictional resource in a plain-text editor. Keep both versions and your test log.")])]
for n,(title,scenes) in enumerate(V,1):
 p=Path(f'video/digital-literacy-2/week-{n:02}/narration');p.mkdir(parents=True,exist_ok=True)
 beats=[dict(id=f'beat-{i+1:02}',title=t,labels=labels,text=text,window=60) for i,(t,labels,text) in enumerate(scenes)]
 (p/'beats.json').write_text(json.dumps(beats,indent=2)+'\n')
 for b in beats:(p/(b['id']+'.txt')).write_text(b['text'])
Path('video/digital-literacy-2/videos.json').write_text(json.dumps([dict(week=i+1,title=x[0]) for i,x in enumerate(V)],indent=2)+'\n')
print('Authored 6 video scripts and 30 narration scenes')
