"""Parallel, lesson-based classroom scenarios; not certification exam items."""
import json
from pathlib import Path
pairs=[]
def q(domain,week,objective,pre,post,why):
 # Each variant: scenario and decision, correct answer, two task-related distractors.
 pairs.append(dict(domain=domain,week=week,objective=objective,pre=pre,post=post,why=why))
q('Technology Basics',1,'1.1',
 ['At your local library, the text on a computer-help webpage is too small. Text in your other apps is comfortable to read. Which change best fits this problem?',
  'Increase the browser zoom for the webpage.', 'Increase display scaling for the whole computer.', 'Increase screen brightness without changing text size.'],
 ['At a community computer lab, text is too small in the word processor, email app and desktop menus. Enlarging one webpage did not help those other areas. Which setting best matches the wider problem?', 'Increase the computer’s display scaling, then check the apps.', 'Increase only the browser’s page zoom again.', 'Change the default printer’s paper size.'],
 {'pre': 'Browser zoom changes the size of webpage content. Display scaling affects the wider desktop, and brightness changes light output. Start with the control that matches the problem, then check the result.', 'post': 'Display scaling affects the wider desktop and its apps. Browser zoom changes webpage content, so it does not solve small menus and text across other programs. Make one adjustment, then check the result.'})
q('Technology Basics',1,'1.2',
 ['A library volunteer is arranging a practice session with you. They need to see when you are busy, but you want to keep appointment names and locations private. Which calendar setting best fits?',
  'Share free/busy availability only.', 'Share event titles and locations with the volunteer.', 'Publish the full calendar for anyone with the link.'],
 ['You are arranging two volunteer visits on different days next week. Both are saved in your calendar. Which view would best help you compare their times with your other appointments?', 'Week view, which shows the days together for checking conflicts.', 'Day view for today, without opening the days of the visits.', 'A task list containing only tasks with no meeting times.'],
 {'pre': 'Free/busy sharing answers the scheduling question without exposing appointment details. Check the actual sharing settings and what the other person can see; sharing a whole calendar may reveal more than the task needs.', 'post': 'Week view helps compare appointments across several days. Day view provides detail for one day; month view gives a broader overview. Check the saved start and end times when looking for conflicts.'})
q('Technology Basics',1,'1.3',
 ['While you draft a message about a library visit, autocorrect replaces your neighbor’s last name with a different word. The changed word is spelled correctly. What should you do before sending?',
  'Restore the intended name and reread the message.', 'Keep the change because the spelling checker accepts it.', 'Rely on the recipient to work out which name you meant.'],
 ['You create a repeating reminder for a Monday library visit. When you check next week, the reminder appears on Tuesday. What should you do before relying on it?', 'Correct the repeat settings and check the next occurrence.', 'Leave the rule alone because automatic reminders must be accurate.', 'Keep adding separate Monday reminders without checking the original rule.'],
 {'pre': 'Autocorrect and autocomplete offer suggestions, not guarantees. Check names, full addresses and meaning yourself. A correctly spelled word or familiar contact can still be wrong for this message.', 'post': 'An automated rule repeats its settings, even when those settings are wrong for the task. Inspect the schedule, correct it and verify the next occurrence instead of assuming automation guarantees the intended result.'})
q('Technology Basics',1,'1.5',
 ['You need 20 copies of a one-page computer-help handout. The lab has two printers, and the print dialog shows the one used yesterday. What should you do before printing the full set?',
  'Confirm the printer, inspect the preview and print one test copy.', 'Send 20 copies to the printer already selected in the dialog.', 'Send one copy to each printer, then use whichever finishes first.'],
 ['Your print preview for a community flyer shows the last line on a second page. You need each flyer to fit on one sheet. What should you do before making copies?', 'Adjust the layout, check the preview again and inspect one test print.', 'Print only page one and let the missing line be left out.', 'Increase the number of copies without changing the layout.'],
 {'pre': 'The selected printer may be left over from another task, and a layout change can alter the output. Confirm the destination and preview, then inspect one test copy before sending the remaining copies.', 'post': 'Preview reveals output problems before you spend paper. Correct the layout without dropping needed content, then inspect a test print. Copy count does not fix a page break.'})
q('Digital Citizenship',4,'2.1',
 ['You use a personal account and a separate volunteer account. Before posting a library event notice, you notice your personal account is active. The notice should come from the volunteer account. What should you do?',
  'Switch accounts and check the posting identity and audience.', 'Post from the personal account and sign the volunteer group’s name.', 'Keep the personal account active and change only its profile photo.'],
 ['You are setting up a separate account for volunteer work. You already have a personal account with a strong password. Which plan best keeps the two accounts protected?', 'Use a different strong password and enable multifactor authentication where available.', 'Reuse the personal password because it is already strong.', 'Give every volunteer the same password so the team can remember it.'],
 {'pre': 'The active account determines the identity attached to a post. A signature or profile picture does not switch accounts. Confirm both your role and the intended audience before posting.', 'post': 'The lesson recommends separate credentials, a trusted password manager and multifactor authentication where available. A reused password can expose more than one account if compromised. Shared passwords also weaken individual control.'})
q('Digital Citizenship',4,'2.2',
 ['It is late at night, and you finish a nonurgent request for a library volunteer. You need a reply by Friday, and the group normally handles messages during daytime hours. Which approach is most considerate?',
  'Send during expected hours and state that a reply is needed by Friday.', 'Mark the message urgent so it gets attention tonight.', 'Ask for an immediate reply without mentioning the Friday deadline.'],
 ['A teammate drafts this nonurgent message: “Look at the flyer soon.” You need their review before the community team meets on Friday. Which revision sets a clear response expectation?', '“Please check the flyer’s contact details and send corrections by Thursday afternoon.”', '“URGENT: look at this whenever you can.”', '“I will keep sending this until you answer.”'],
 {'pre': 'Match message timing to urgency and the group’s expectations. A specific deadline tells the recipient when to act. For a nonurgent task, an urgent label or repeated reminders creates needless pressure.', 'post': 'A useful request states what needs checking and when a response is needed. A clear deadline supports planning; vague timing, an unnecessary urgent label and repeated messages do not clarify the task.'})
q('Digital Citizenship',4,'2.2',
 ['During a library practice session, a partner asks what an abbreviation in your instructions means. You do not know their past computer experience. Which response best helps them continue?',
  'Explain the term in plain language and ask whether an example would help.', 'Repeat the abbreviation more slowly without explaining it.', 'Take over the task because their question shows they cannot do it.'],
 ['A volunteer guide begins, “Older people will need someone else to do this for them.” The class includes people with varied experience. Which replacement best supports everyone’s participation?', '“Try these steps at your own pace, and ask for help where you need it.”', '“Everyone over a certain age should skip the practice.”', '“Anyone who needs help should watch instead of trying.”'],
 {'pre': 'Explain the unfamiliar term and connect it to the task. One question does not tell you someone’s overall ability. Plain language and an offer of help support learning without making assumptions.', 'post': 'Inclusive language avoids assuming ability from age. Offer clear steps, time to practice and help based on the person’s needs. Learners bring different prior experience and should have a chance to participate.'})
q('Digital Citizenship',1,'2.3',
 ['You want to change an app’s download folder, but its menus changed after an update. An older printed guide shows a button you cannot find. What is the most useful next step?',
  'Use official help for the current version and search for changing the download folder.', 'Keep looking only for the old button shown in the printed guide.', 'Install an unfamiliar repair tool that promises to restore all old menus.'],
 ['A library practice document will not save. You have tried Save As, but the app still displays “Folder unavailable.” Which request would give official support the most useful starting information?', 'Name the app and version, the save task, what you tried and the exact error.', 'Say only “My computer does not work” and wait for a guess.', 'Send your account password instead of describing the problem.'],
 {'pre': 'Current official help is a good starting point when menus change. Identify the app version and the task, rather than relying only on old button positions. When asking for help, describe what you tried and what happened.', 'post': 'A precise help request names the application, task, attempted steps and error. This helps someone give instructions that fit. A password is not needed to explain the problem.'})
q('Information Management',2,'3.1',
 ['You want an in-person computer-help session at a public library near Beckley, West Virginia. Which search gives the search engine the clearest description of your need?',
  'Beckley WV public library computer help sessions', 'computer help anywhere online', 'West Virginia community activities'],
 ['Searching for “classes” returns cooking, exercise and computer lessons across the country. You need beginner computer instruction near Charleston, West Virginia. Which revision would make the results more useful?', 'Search for “beginner computer classes Charleston WV.”', 'Search for “classes” again without adding any details.', 'Search for “popular activities” and rely on the first result.'],
 {'pre': 'Useful search terms name the service, place and setting you need. These searches are starting points, not proof that a class exists. Confirm current details with the library before making plans.', 'post': 'Refine a broad search with the subject, audience and location. These terms describe the task more clearly; search results still need checking for current availability and suitability.'})
q('Information Management',2,'3.2',
 ['A shared post says every library in your county offers free laptop loans. It gives no source or date. You want to borrow a laptop from your local library. What is the best way to check the claim?',
  'Contact that library through its official website or known phone number.', 'Treat the number of shares as proof that the offer is available.', 'Rely on another directory that repeats the same unsourced claim.'],
 ['A page selling a paid computer course says it is the only reliable way to learn. It provides no evidence for that claim. How should you judge the recommendation?', 'Consider the seller’s interest and compare the claim with independent evidence.', 'Accept it because a business would not promote its own course unfairly.', 'Assume that a polished layout proves the claim.'],
 {'pre': 'Verify a service with the organization responsible for providing it. Search position, appearance and repeated claims do not establish current availability. Check the details that matter for your visit.', 'post': 'A source’s purpose and interests can shape its claims. Check evidence and compare relevant sources. A commercial interest does not make every statement false, but it is a reason to examine the support for a recommendation.'})
q('Information Management',2,'3.2',
 ['You need computer help you can attend locally in West Virginia. You find a current, accurate library page, but the class is in another state and is in person only. Why does this page not meet your need?',
  'The information can be accurate but not relevant to your location.', 'Any page about a library must apply to your local library too.', 'A current page is enough to show that the class is available nearby.'],
 ['You find an official local workshop announcement from three years ago. It accurately describes the event held then, but you need a session you can attend now. What still needs checking?', 'Whether the program still runs and what its current schedule is.', 'Only whether the old announcement has a familiar logo.', 'Nothing; an accurate past announcement guarantees a current session.'],
 {'pre': 'Accuracy and relevance are different checks. A trustworthy page can describe a real class that does not fit your location or attendance needs. Use the source that answers your actual question.', 'post': 'Currency matters even when a source is accurate and local. Verify whether the service still operates and whether dates, eligibility or arrangements have changed before relying on an older announcement.'})
q('Information Management',2,'3.3',
 ['In the fictional library practice form, you need to request computer help. The form has required fields and several optional fields. What should you check before entering information?',
  'Who receives it, why it is needed and which fields the request requires.', 'How to fill every optional field, even when it adds unrelated details.', 'Whether entering extra private details will move the request ahead of others.'],
 ['After submitting the fictional computer-help form, you see a confirmation for “phone help,” although you intended an in-person visit. What does checking this confirmation tell you to do?', 'Use the available correction or contact method to fix the requested help type.', 'Assume the confirmation is unimportant because the form was submitted.', 'Submit several more requests without checking whether they replace the first.'],
 {'pre': 'Check who collects the information, the purpose and the required fields. Optional does not mean necessary. In class, use fictional details; review the completed request and read its confirmation.', 'post': 'The confirmation is evidence of what the system received. Check that it matches your intended request, then use the stated correction or contact process. Repeated submissions can create duplicates rather than repair the original.'})
q('Content Creation',3,'4.1',
 ['You are making a library handout with sections called Getting started, Practice steps and Where to get help. Readers should be able to navigate its sections, including with a screen reader. How should you mark the section titles?',
  'Apply the document’s appropriate heading styles.', 'Make the titles bold but leave them as ordinary paragraphs.', 'Insert extra blank lines above each title without using headings.'],
 ['Your handout’s section titles look large and bold, but the document’s heading navigation does not list them. What is the most useful correction?', 'Apply real heading styles to the section titles.', 'Make the same ordinary paragraphs even larger.', 'Add more blank lines before each title.'],
 {'pre': 'Heading styles give section titles structural meaning, which helps navigation and assistive technology. Bold, font size and spacing can change appearance without creating that structure.', 'post': 'Visual formatting alone may leave titles as ordinary paragraphs. Heading styles add document structure that navigation and assistive technology can recognize. Check the structure as well as how the page looks.'})
q('Content Creation',3,'4.1',
 ['Your practice budget lists paper at $12 in B2, folders at $8 in B3 and pens at $5 in B4. You want a total that updates if any cost changes. Which formula belongs in the total cell?',
  '=SUM(B2:B4)', '=B2+B4', '=25'],
 ['A practice budget shows three costs: 12, 8 and 5, with a total of 25. You want to check whether the total really uses all three cells. Which test gives useful evidence?', 'Change 12 to 15 and check that the total updates to 28.', 'Change the total cell’s color and check that it stays 25.', 'Rename the worksheet and assume the total is now verified.'],
 {'pre': 'The colon includes every cell in the range, including the middle row. Adding only the first and last cells misses an item. A fixed number can look correct now but will not update when an input changes. Test the formula by changing one input.', 'post': 'Changing an input checks calculation behavior. The total should increase by the same amount, from 25 to 28. If it does not, inspect the formula’s range and whether inputs are stored as numbers; formatting is not a calculation test.'})
q('Content Creation',3,'4.3',
 ['You find a photograph through an image search and want to add it to a community handout. The search preview does not show reuse terms. What should you do before using it?',
  'Open the source, check allowed uses and follow any required credit conditions.', 'Use it with the creator’s name because credit alone always grants permission.', 'Use it without checking because the handout will be given away free.'],
 ['A practice image has written permission allowing reuse and cropping if the creator, title, source and license are credited. You want to crop it for a flyer. Which plan follows those stated conditions?', 'Crop a copy and include the required credit with the reused image.', 'Crop it and omit the credit because only part of the image remains.', 'Keep only the creator’s name because the other required details are optional.'],
 {'pre': 'Find the actual license or permission and follow its conditions, including whether changes are allowed and what credit is needed. Credit, a screenshot or free distribution does not by itself establish permission. Use an approved alternative if permission is unclear.', 'post': 'Read and follow the permission actually supplied. In this fictional example, cropping is allowed but the stated credit is still required. Save a copy so the original stays available.'})
q('Content Creation',3,'4.4',
 ['A partner needs to rewrite two paragraphs in your workshop handout. You want them to edit the wording directly. Which file and access best support that task?',
  'An editable document with permission for the partner to edit.', 'A picture of the page that lets the partner see the wording.', 'An editable document shared with view-only permission.'],
 ['Your finished community handout is ready for neighbors to read and print. They do not need to edit it, and you want to preserve its page layout. Which delivery fits that purpose?', 'Export a PDF, then open it to check page breaks, links and missing content.', 'Export CSV because it preserves document layout and images.', 'Send a photo of the screen without checking whether all the text is readable.'],
 {'pre': 'Direct revision needs both an editable format and permission to edit. A screenshot shows the content but does not provide editable paragraphs. A view-only link also prevents the intended task; a checked PDF can be useful later for finished distribution.', 'post': 'PDF is useful for distributing a finished layout. Open the exported file to inspect it; export success alone does not prove the result is usable. CSV is for simple table data and does not preserve this document’s layout.'})
q('Communication',4,'5.1',
 ['You are emailing the library to ask which room will host its computer-help session. Which subject line best tells the recipient what you need?',
  'Please confirm the room for the computer-help session', 'A question about something at the library', 'Computer-help session room confirmed'],
 ['Your email to a community organizer already has a clear subject. The body only says, “Here is the flyer.” You need the organizer to check the room number before printing. What should you add?', 'A specific request to verify the room number, with the deadline and attached draft.', 'More praise for the flyer without saying what needs checking.', 'A second copy of the same attachment without explaining the task.'],
 {'pre': 'A useful subject names the topic and the action needed. A vague subject hides the request, while saying something is confirmed incorrectly suggests the question is already settled. Put the needed context in the message as well.', 'post': 'The body needs enough context and a clear next action, even when the subject is good. State what the recipient should check and when, then verify the intended recipient and attachment before sending.'})
q('Communication',4,'5.1',
 ['You are sending a workshop announcement to people who do not need to see one another’s email addresses. Which choice hides that recipient list from the other recipients?',
  'Place those addresses in Bcc.', 'Place those addresses in Cc.', 'Place all those addresses in To.'],
 ['You sent a volunteer announcement using Bcc. A partner says this also prevents recipients from forwarding its contents. Which statement correctly explains the limit?', 'Bcc hides those recipient addresses; it does not stop forwarding the message.', 'Bcc encrypts the message and makes forwarding impossible.', 'Bcc removes the attachment as soon as a recipient opens it.'],
 {'pre': 'Bcc hides those recipient addresses from other recipients; To and Cc normally show them. Bcc does not encrypt the message, stop forwarding or make an attachment safe.', 'post': 'Bcc controls visibility of recipient addresses, not what recipients can do with the content. It does not encrypt the message or prevent forwarding. Consider the content’s sensitivity before sending it.'})
q('Communication',4,'5.2',
 ['A fictional design app offers a seven-day free trial for making a community flyer. You only need it for one project. What should you check before starting the trial?',
  'Whether it renews, what it will cost and how and when to cancel.', 'Only whether the first seven days are free.', 'Only whether deleting the app removes it from the computer.'],
 ['A fictional app trial says: “No charge for seven days; then $8 each month unless canceled.” You only need the app for one weekend. Which conclusion follows from these terms?', 'Keeping the trial active after seven days can start a recurring charge.', 'Deleting its desktop shortcut ends the subscription automatically.', 'The seven free days mean all later use will also be free.'],
 {'pre': 'Look beyond the introductory price to renewal and cancellation terms. Removing an app is not the same as following the service’s cancellation process. The class uses fictional offers and does not require a real purchase.', 'post': 'Read the later price and renewal schedule, not just the introductory offer. Follow the stated cancellation process if you do not want renewal. Removing a shortcut does not establish cancellation. This is a fictional offer, not a real purchase.'})
q('Communication',4,'5.2',
 ['You downloaded a fictional photo app for free. A new button offers extra templates for a one-time $4 charge. What should you do before choosing that upgrade?',
  'Review the separate purchase and its terms before deciding whether to authorize it.', 'Assume the templates are free because the app cost nothing to download.', 'Approve the purchase first and check what it costs afterward.'],
 ['A fictional free game offers a $2 upgrade. Its purchase screen also offers a way to require approval for future purchases. Why is that control useful?', 'It can help prevent additional purchases from being authorized without review.', 'It makes every paid upgrade free from then on.', 'It proves that no charge has ever been made in the app.'],
 {'pre': 'The download price and the price of an extra feature are separate. Read the purchase details before authorizing anything; do not assume when or whether a charge applies. No real payment is needed for the practice.', 'post': 'Purchase controls help manage later transactions; they do not erase charges or turn paid features into free ones. Review the offer, authorization settings and receipts. Class practice does not require making a real purchase.'})
q('Collaboration',4,'6.1',
 ['Two library volunteers open the same shared handout during a live call. Both edit it while discussing their changes. Which description fits the way they are working?',
  'Synchronous collaboration: working together at the same time.', 'Asynchronous collaboration: leaving work for someone to review later.', 'Independent copies: each person edits a separate file.'],
 ['Two volunteers cannot work at the same time. One can draft a handout today, and the other can review it tomorrow. Which plan fits their schedules while keeping one shared copy?', 'Leave comments in the shared draft for the other person to review later.', 'Require both volunteers to type in the file during a live call today.', 'Create separate copies without agreeing how changes will be combined.'],
 {'pre': 'Synchronous means working together at the same time. Asynchronous work happens at different times, such as leaving comments for tomorrow. Online storage and separate computers do not determine which timing pattern the team uses.', 'post': 'Asynchronous collaboration supports work at different times. A shared draft and clear comments let the next person continue the task. A live session does not fit these schedules, and unmanaged copies can create conflicting versions.'})
q('Collaboration',4,'6.1',
 ['Your library handout needs a partner’s feedback. They should leave comments, but you will make the wording changes. The sharing tool offers Viewer, Commenter and Editor. Which access best fits?',
  'Commenter for the named partner.', 'Viewer for the named partner.', 'Editor for anyone with the link.'],
 ['A named reviewer has finished commenting on your draft. You now ask that person to make the agreed corrections directly, while everyone else should still only read it. What access change fits?', 'Give that reviewer editing access and keep the others as viewers.', 'Make anyone with the link an editor to avoid changing one person’s role.', 'Keep the reviewer view-only and expect direct edits to work.'],
 {'pre': 'Commenter access supports feedback without direct rewriting. Viewer access does not provide the requested commenting ability in this scenario, and a public editing link gives more access than the task requires.', 'post': 'Match access to the current task and the named people who need it. Direct corrections require editing access; that does not justify giving every reader the same permission. Review sharing after the work is complete.'})
q('Collaboration',4,'6.1',
 ['A partner’s computer-help handout says “contact us” but gives no phone number or other contact method. Which comment best explains a useful revision?',
  'Add a contact method after the steps so readers know how to get help.', 'Make the handout better before we share it.', 'Change the title color; that should solve the missing contact information.'],
 ['A partner comments, “Add the help desk’s contact method after step 3 so readers know where to ask questions.” You are responsible for revising the handout. What is a useful response?', 'Add the verified contact information and acknowledge how you addressed the comment.', 'Delete the comment without checking the missing information.', 'Change the background color and mark the contact issue resolved.'],
 {'pre': 'Useful feedback identifies the specific problem, suggests a change and explains how readers benefit. Vague criticism leaves the author guessing. A cosmetic change does not supply missing information.', 'post': 'Constructive collaboration includes acting on specific feedback and communicating what changed. Resolve a comment when its issue is addressed, or ask a focused question if the requested change is unclear. An unrelated visual change does not solve the stated problem.'})
q('Collaboration',4,'6.2',
 ['You want to record an online volunteer meeting so an absent partner can review it. Participants will be visible and speaking. What should happen before you start recording?',
  'Check the organizer’s rules and obtain the appropriate recording permission.', 'Assume joining the meeting means everyone agreed to be recorded.', 'Start recording because the meeting software offers a Record button.'],
 ['During a live workshop call, background noise from your room makes it hard for others to hear the speaker. You are listening and do not need to speak yet. What should you do?', 'Mute your microphone and unmute when it is your turn to speak.', 'Raise your speaker volume to cover the noise.', 'Start a recording so the background noise will stop.'],
 {'pre': 'The presence of a Record button or an invitation does not establish recording permission. Check the organizer’s rules and the appropriate permissions before recording participants. A helpful purpose does not replace that check.', 'post': 'Meeting etiquette includes controlling background noise, taking turns and using mute appropriately. Muting your microphone stops your room’s sound from being sent; speaker volume and recording controls do not solve that problem.'})
q('Safety and Security',5,'7.1',
 ['One learner uses a keyboard instead of a mouse. Another needs captions to follow spoken directions. Which version of a library learning page supports both needs?',
  'A page with keyboard-operated controls and captioned videos.', 'A page with captions but controls that require a mouse.', 'A page with keyboard controls but spoken directions available only as audio.'],
 ['A practice page marks completed steps only in green and unfinished steps only in red. Some learners cannot distinguish those colors. Which change makes the status clearer?', 'Add visible “Complete” and “Not yet” labels beside the colored indicators.', 'Use brighter red and green but keep color as the only signal.', 'Move the color key to the bottom without labeling the steps.'],
 {'pre': 'Flexible input and captions address different needs. Providing both lets more people complete the same task in different situations. Supporting one need does not remove the other barrier.', 'post': 'Do not rely on color alone to communicate meaning. Text labels provide the same information for people who perceive colors differently and for situations where color is hard to see.'})
q('Safety and Security',5,'7.2',
 ['In a fictional online group, a new contact quickly becomes friendly, claims to be a local volunteer and asks for private information. You have not verified their identity. What is the best response?',
  'Pause the request and verify their identity through a separate trusted route.', 'Trust the request because the profile includes local photos.', 'Ask the same contact to promise the profile is real, then send the information.'],
 ['Notifications from a community group keep pulling you away from your practice task. You feel you must check every alert so you do not miss out. Which response supports your own learning goal?', 'Adjust nonessential alerts and choose a planned time to check the group.', 'Open every alert immediately, even when it interrupts the task.', 'Join more groups so you are less likely to miss an update.'],
 {'pre': 'A false identity used to build trust is called catfishing. This scenario does not prove the person is an impostor, but friendliness and local photos do not verify identity. Pause and check through a separate trusted route before sharing private information.', 'post': 'Fear of missing out can encourage repeated checking. Choose notification settings, breaks and checking times that support your own goals. You can remain part of a group without responding to every alert immediately.'})
q('Safety and Security',5,'7.3',
 ['You find an unknown USB drive beside a computer in the library lab. You would like to return it to its owner. What is the safest next step?',
  'Give it to the instructor or authorized staff without connecting it.', 'Plug it into a lab computer to look for the owner’s name.', 'Try it on your own laptop so the shared lab computer is not affected.'],
 ['A webpage that only displays a written community schedule asks to use your camera. Nothing in your task needs a photo or video call. What is the most appropriate choice?', 'Deny camera access because the permission does not fit the task.', 'Allow access because every permission request is required to read a page.', 'Allow it because the page uses a familiar community logo.'],
 {'pre': 'An unknown drive can carry harmful software. Its label and appearance do not prove it is safe, and switching computers does not remove the risk. Let authorized staff handle it without connecting it yourself.', 'post': 'A permission request should fit a clear task and a trusted app. Reading a written schedule does not need the camera. A logo is not a reason to grant unrelated access; review the setting if a legitimate need arises later.'})
q('Safety and Security',5,'7.3',
 ['A practice file can still be read even after you mark it read-only. You want to protect its readable contents if someone gets a copy without the needed key. Which feature addresses that goal?',
  'Encryption of the file’s contents.', 'Read-only settings that restrict editing.', 'A ZIP archive created without encryption.'],
 ['Your practice laptop uses device encryption, but you leave it unlocked and signed in at a shared table. What protection is still needed when you step away?', 'Lock the session so another person cannot use the open account.', 'Nothing; encryption makes an unlocked account inaccessible to everyone else.', 'Rename the files so the open account can safely remain unattended.'],
 {'pre': 'Encryption protects readable data by requiring the appropriate key or authorized access. Read-only settings restrict changes, renaming changes a label, and an ordinary ZIP is not automatically encrypted. An unlocked account or device still needs protection.', 'post': 'Encryption can protect stored data without the required key, but it does not prevent someone using an already unlocked session. Lock or sign out of the device as appropriate when leaving it. File names do not control access.'})
variants={}
for kind in ['pre','post']:
 items=[]
 for i,p in enumerate(pairs):
  question,correct,*wrong=p[kind]
  choices=[correct,*wrong]; offset=(i+(1 if kind=='post' else 0))%3
  choices=choices[offset:]+choices[:offset]
  items.append(dict(id=f'{kind}-{i+1:02}',pair=i+1,domain=p['domain'],week=p['week'],objective=p['objective'],question=question,options=choices,answer=choices.index(correct),why=p['why'][kind]))
 variants[kind]=items
Path('courses/digital-literacy-2/assets/questions.json').write_text(json.dumps(variants,indent=2)+'\n')
print('Authored',len(pairs),'parallel scenario pairs; 4 questions per domain')
