"""Render the reusable course and its print materials from one curriculum source."""
import json,html,base64
from workshops import for_slide,workshop
import learning
import scenes as slide_scenes
import photo_scenes
from pathlib import Path
ROOT=Path('courses/digital-literacy-2'); BASE='/courses/digital-literacy-2'
C=json.loads(Path('scripts/dl2/curriculum.json').read_text()); W=C['weeks']; Q=json.loads((ROOT/'assets/questions.json').read_text())
def e(t): return html.escape(str(t),quote=True)
def link(path,label,cls=''):return f'<a class="{cls}" href="{BASE}/{path}">{e(label)}</a>'
def ul(items):return '<ul>'+''.join('<li>'+e(x)+'</li>' for x in items)+'</ul>'
def challenge_table(c):
 rows=''
 for k,(task,materials,_) in enumerate(c['tasks']):
  rating=''.join(f'<label><input type="radio" name="challenge-rating-{k}" value="{e(r)}"> {e(r)}</label>' for r in c['ratings'])
  rows+=f'<tr><td>{e(task)}</td><td>{e(materials)}</td><td><label class="visually-hidden" for="challenge-answer-{k}">What you did for task {k+1}</label><textarea class="worksheet-input" id="challenge-answer-{k}"></textarea><div class="print-answer"></div></td><td><fieldset class="rating"><legend class="visually-hidden">Instructor rating for task {k+1}</legend>{rating}</fieldset></td></tr>'
 return f'<p>{e(c["intro"])}</p><div class="table-scroll"><table class="challenge"><thead><tr><th>Task</th><th>Materials</th><th>What you did</th><th>Instructor rating</th></tr></thead><tbody>{rows}</tbody></table></div>'
def challenge_key(c):return '<p>Evidence to look for on each row:</p><ol>'+''.join(f'<li><strong>{e(task)}.</strong> {e(evidence)}</li>' for task,_,evidence in c['tasks'])+'</ol>'
def page(title,body,cls='doc',week=None,script='lesson.js'):
 if script=='assessment.js':
  seal=base64.b64encode(Path('assets/vub-seal-white.png').read_bytes()).decode()
  body+=f'<template id="report-brand"><img class="report-seal" src="data:image/png;base64,{seal}" alt="WV Veterans Upward Bound seal"></template>'
 if cls!='lesson':body=learning.frame(body)
 return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{e(title)} — practical VUB Digital Literacy Level 2 learning."><title>{e(title)} | VUB Learning</title><link rel="stylesheet" href="/shared/brand.css"><link rel="stylesheet" href="{BASE}/assets/course.css"><link rel="stylesheet" href="{BASE}/assets/workshop.css"><link rel="stylesheet" href="{BASE}/assets/learning-app.css">{f'<link rel="stylesheet" href="{BASE}/assets/slide-scenes.css">' if cls=="lesson" else ""}{('<style id="result-report-style">'+(ROOT/'assets/results-report.css').read_text()+'</style>') if script=='assessment.js' else ''}</head>
<body class="{cls}" {f'data-week="{week}"' if week else ''}>
{learning.CONTRACT}
<a class="skip" href="#main">Skip to content</a><header class="topbar"><a class="brand" href="/"><img src="/assets/vub-seal-white.png" alt=""><span>VUB Learning</span></a><span class="course-name">Digital Literacy · Level 2</span>{link('index.html','Course home')}</header><div class="brand-line"></div>
{body}
<footer class="footer">WV Veterans Upward Bound · Build technology confidence through practice.</footer>
<script src="/shared/progress.js"></script><script src="/shared/text-size.js"></script><script src="{BASE}/assets/{script}"></script><script src="{BASE}/assets/workshop.js"></script><script src="{BASE}/assets/learning-app.js"></script>{f'<script src="{BASE}/assets/slide-scenes.js"></script>' if cls=="lesson" else ""}</body></html>'''
def chapters(n,video_id):
 p=Path(f'video/digital-literacy-2/week-{n:02}/narration/beats.json')
 if not p.exists():return ''
 beats=json.loads(p.read_text())
 if not all('start' in b for b in beats):return ''
 demo_path=p.parent.parent/'screen-share-actions.json'
 demo_chapters={s['chapter'] for s in json.loads(demo_path.read_text())} if demo_path.exists() else set()
 items=''.join(f'<li><button type="button" data-video-seek="{b["start"]:.3f}"><time datetime="PT{b["start"]:.3f}S">{int(b["start"])//60}:{int(b["start"])%60:02}</time>{e(b["title"])}{(" · Screen demo" if i+1 in demo_chapters else "")}</button></li>' for i,b in enumerate(beats))
 return f'<details class="video-chapters"><summary>Choose a chapter or replay a skill</summary><nav aria-label="Video chapters" data-video-chapters="{video_id}"><p>Selecting a chapter pauses the video at that point. Use Play when you are ready.</p><ol>{items}</ol></nav></details>'
def write(path,text):p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
def doc(title,body):return page(title,f'<main class="page doc" id="main"><h1>{e(title)}</h1><div class="actions"><button type="button" data-print>Print / Save as PDF</button>{link("index.html","Course home","button secondary")}</div>{body}</main>')
def resources(n):
 p=f'weeks/week-{n:02}'
 return ''.join(link(x,y) for x,y in [(p+'/worksheet.html','Worksheet'),(p+'/lesson-plan.html','Instructor lesson plan'),(p+'/answer-key.html','Worksheet answer guide'),(p+'/video-transcript.html','Video and transcript'),('syllabus.html','Syllabus'),('assessments/pre-test.html','Pre-test'),('assessments/post-test.html','Post-test')])
def exercise(s,n,i):
 k=s['kind']; prefix=f'w{n}s{i}'
 if k=='steps': return '<ol class="step-list interactive-steps">'+''.join('<li><button type="button" data-step-done aria-pressed="false"><span>'+e(x)+'</span><span class="step-state">Mark practiced</span></button></li>' for x in s['items'])+'</ol>'
 if k=='flip':return '<div class="flip-grid">'+''.join(f'<button class="flip" type="button" aria-expanded="false" aria-label="{e(a)}: reveal explanation"><span class="flip-inner"><span class="flip-front" aria-hidden="false">{e(a)}<span class="flip-hint">Select to reveal</span></span><span class="flip-back" aria-hidden="true">{e(b)}<span class="flip-hint">Select to turn back</span></span></span></button>' for a,b in s['cards'])+'</div>'
 if k=='check':return f'<div class="check-options" data-explanation="{e(s["why"])}">'+''.join(f'<button type="button" aria-pressed="false" data-correct="{str(j==s["answer"]).lower()}">{e(o)}</button>' for j,o in enumerate(s['options']))+'</div><p class="feedback" role="status"></p>'
 if k=='video':return f'<video {("poster="+chr(34)+photo_scenes.PHOTO_ROOT+photo_scenes.PHOTOS[n][1]+".webp"+chr(34)) if n!=5 else ""} id="lesson-video" tabindex="0" controls preload="metadata" playsinline aria-label="Week {n} explainer"><source src="{BASE}/media/week-{n:02}.mp4" type="video/mp4"><track kind="captions" src="{BASE}/media/week-{n:02}.vtt" srclang="en" label="English" default></video><p class="video-caption">Captions are available in the player. {link(f"weeks/week-{n:02}/video-transcript.html","Read the full transcript")}.</p>'+chapters(n,"lesson-video")
 if k=='lab':return link(f'weeks/week-{n:02}/worksheet.html','Open the activity worksheet','button')
 if k=='assessment':return link(f'assessments/{s["href"]}-test.html','Open the '+s['href']+'-test','button')
 if k=='form':return '<form id="practice-form" class="exercise"><label for="practice-topic">Help topic (required)</label><select id="practice-topic" name="topic" required><option value="">Choose a topic</option><option>Finding a file</option><option>Using a calendar</option></select><label for="practice-method">Practice contact method (required)</label><select id="practice-method" name="method" required><option value="">Choose a method</option><option>Fictional email reply</option><option>Ask at the desk</option></select><div class="actions"><button type="submit">Review practice request</button><button type="reset" class="secondary">Reset practice form</button></div><p id="form-result" class="sim-status" role="status"></p></form>'
 if k=='permissions':return '<div class="exercise"><label for="permission">Alex needs to suggest wording. Choose access:</label><select id="permission"><option value="">Choose permission</option><option value="viewer">Viewer</option><option value="commenter">Commenter</option><option value="editor">Editor</option></select><p id="permission-result" class="sim-status" role="status">This simulation changes no real file access.</p></div>'
 if k=='spreadsheet':return '<div class="interactive-calc"><label for="paper-cost">Paper cost ($)</label><input id="paper-cost" type="number" min="0" step="1" value="12"><output id="budget-total" for="paper-cost" aria-live="polite">Total: $25.00</output></div><p class="small">Folders: $8 · Pens: $5. In a spreadsheet, enter the formula yourself.</p>'+link('assets/supplies.csv','Download the practice CSV','button secondary')
 if k=='starter':return '<div class="actions">'+link('activities/resource-finder.html','Open starter app','button')+f'<a class="button secondary" href="{BASE}/activities/resource-finder.html" download="resource-finder-v1.html">Download editable HTML</a></div>'
 return ''
for w in W:
 n=w['n']; folder=f'weeks/week-{n:02}'
 slides=[dict(title=f'Week {n}: '+w['title'],body=w['summary'],kind='objectives')]+w['slides']+[dict(title='You completed this lesson',body='Name one thing you can now do and one next practice step. Revisit any slide when you need it.',kind='complete')]
 nav=''.join(f'<button class="slide-link" type="button" data-slide="{i}" aria-current="false">{i+1}. {e(s["title"])}</button>' for i,s in enumerate(slides))
 sections=''
 for i,s in enumerate(slides):
  more=ul(w['objectives']) if s['kind']=='objectives' else exercise(s,n,i)
  if s['kind']=='complete':more='<div class="actions">'+link(f'weeks/week-{n+1:02}/presentation.html','Continue to next week','button')+'</div>' if n<6 else link('index.html','Return to your course','button')
  demo=photo_scenes.special(n,i+1) or for_slide(n,i+1) or slide_scenes.feature(n,i+1)
  if s['kind']=='objectives':
   demo=photo_scenes.sequence(photo_scenes.EVIDENCE[n]) if n in [1,2] else workshop({3:'sheet',4:'feedback',5:'phishing',6:'app'}[n])
   more='<details class="concept-note" open><summary>What you will learn</summary>'+more+'</details>'
  if demo:
   content=('' if (n,i+1)==(5,3) else photo_scenes.photo(n,i+1,compact=s['kind']!='objectives'))+('' if s['kind']=='objectives' else f'<p class="slide-lead">{e(s["body"])}</p>')+demo+more
  else:
   art=slide_scenes.supporting(s,n,i+1)
   content=(f'<div class="illustrated-copy">{art}<div><p>{e(s["body"])}</p>{more}</div></div>' if art else f'<p>{e(s["body"])}</p>'+more)
  content+=photo_scenes.supplement(n,i+1)
  sections+=f'<section class="slide slide-kind-{s["kind"]} {"has-workshop" if demo else ""} {"summary" if s["kind"] in ["summary","complete"] else ""}" id="slide-{i+1}" aria-labelledby="title-{i+1}"><h2 id="title-{i+1}" tabindex="-1">{e(s["title"])}</h2>{content}</section>'

 body=f'<button type="button" class="menu-toggle" aria-expanded="false" aria-controls="lesson-sidebar">Show lesson navigation</button><div class="deck-layout"><aside class="sidebar" id="lesson-sidebar" aria-label="Lesson navigation"><h2>Week {n} · Lesson contents</h2><nav aria-label="Slides">{nav}</nav><nav class="resources" aria-label="Week resources">{resources(n)}</nav></aside><main class="deck-main" id="main"><div class="deck-toolbar"><p>Week {n} · {e(w["title"])}</p><button type="button" class="secondary" id="restart">Start from first slide</button></div><progress id="lesson-progress" value="1" max="{len(slides)}" aria-label="Lesson progress"></progress>{sections}<div class="bottom-nav"><button type="button" id="previous">Previous slide</button><span id="slide-counter" role="status"></span><button type="button" id="next">Next slide</button></div><p class="muted small">Use arrow keys, Page Up / Page Down, Home / End outside a control. Swipe horizontally on touch screens. Your slide position is saved in this browser.</p></main></div>'
 write(folder+'/presentation.html',page(w['title'],body,'lesson',n))
 worksheet='<p>'+e(w['summary'])+'</p><p>Name or learner code: ____________________</p><p>Use fictional information. Work with a partner, take turns, and record what you actually observed. Type below or print a blank copy. Typed worksheet responses stay on this page only; print before closing.</p>'
 for i,prompt in enumerate(w['lab']):worksheet+=f'<section class="question"><h2>{i+1}. {e(prompt)}</h2>'+(challenge_table(w['challenge']) if w.get('challenge',{}).get('item')==i else f'<label class="visually-hidden" for="answer-{i}">Response to activity {i+1}</label><textarea class="worksheet-input" id="answer-{i}"></textarea><div class="print-answer"></div>')+'</section>'
 if n==5:worksheet+='<div class="actions">'+link('assets/supplies.csv','Practice workbook data (from week 3)','button secondary')+'</div>'
 if n==3:worksheet+='<div class="actions">'+link('assets/supplies.csv','Practice workbook data','button secondary')+link('assets/community-resource.svg','Original practice image','button secondary')+'</div>'
 if n==6:worksheet+='<div class="actions">'+link('activities/resource-finder.html','Open starter app','button')+f'<a class="button secondary" href="{BASE}/activities/resource-finder.html" download="resource-finder-v1.html">Download editable HTML</a></div>'+''.join(f'<h2>{e(t)}</h2><ol class="procedure">'+''.join('<li>'+e(x)+'</li>' for x in steps)+'</ol>' for t,steps in w['procedures'])+'<h2>App test log</h2><table><thead><tr><th>Test</th><th>Expected result</th><th>Actual / pass or fail</th></tr></thead><tbody>'+''.join('<tr><td>'+t+'</td><td>________________</td><td>________________</td></tr>' for t in ['Blank search','Matching name','No match','Mixed case','Category filter','Keyboard only','Narrow screen'])+'</tbody></table><h2>Extension rubric</h2><p>Score each item 0 (not yet), 1 (with help) or 2 (independently). This 8-point extension score is separate from the 28-point GS6 classroom assessment.</p>'+ul(['Defines a useful task and observable requirements.','Builds a working search/filter prototype with fictional data.','Tests keyboard, empty and narrow-screen behavior; records a revision.','Explains the code, storage and limits before real hosting.'])
 write(folder+'/worksheet.html',doc(f'Week {n} activity worksheet',worksheet))
 key='<p>Instructor guide. Accept equivalent evidence-based answers. These activities evaluate demonstrated skills, not speed.</p>'+''.join(f'<section class="question"><h2>{i+1}. {e(w["lab"][i])}</h2><p class="answer-model">{e(a)}</p>'+(challenge_key(w['challenge']) if w.get('challenge',{}).get('item')==i else '')+'</section>' for i,a in enumerate(w['answers']))
 write(folder+'/answer-key.html',doc(f'Week {n} worksheet answer guide',key))
 plan=f'<p>{e(w["summary"])}</p><h2>Learning outcomes</h2>{ul(w["objectives"])}<h2>Prepare the room</h2><p>Provide a workstation and headphones for each learner, this lesson and worksheet, a word processor and spreadsheet app. Use instructor-provided fictional accounts or a modeled demonstration for cloud tasks. Test the local video and printer destination before class. No paid service, real purchase or new learner account is required.</p><p>For unavailable features, use the course simulation or role play and label the evidence as simulated. For week 6, supply a plain-text editor and the downloadable starter app; use an approved AI tool only if available.</p><h2>Two-hour teaching plan</h2><table><thead><tr><th>Minutes from start</th><th>Phase</th><th>Instructor and learner actions</th></tr></thead><tbody>'
 time=0
 for minutes,phase,action in w['agenda']:
  plan+=f'<tr><td>{time}–{time+minutes} ({minutes} min)</td><td>{e(phase)}</td><td>{e(action)}</td></tr>';time+=minutes
 assert time==120
 plan+='</tbody></table><h2>Using the chaptered video</h2><p>Use relevant chapters during the demonstration phases, within the existing time allocation. The full video provides approximately seven to eight minutes of instruction; paused practice uses the scheduled lab time. Ask learners to choose a familiar community or household task, predict the result before the demonstration, and explain the evidence afterward. Replay only the chapter needed for a refresher. Do not add the video as extra time on top of the two-hour plan.</p><h2>Facilitation and access</h2><p>Demonstrate slowly, then let learners try. Offer keyboard and mouse paths, captions and the written transcript. Print large copies if needed. Pair a driver and coach, then switch. Provide extra practice time without requiring learners to disclose a disability.</p><h2>Evidence to collect</h2>'+ul(w['lab'])+'<h2>Feedback and differentiation</h2><p>Ask the learner to explain a choice and demonstrate the result. Mark Independent, With prompt, or Needs practice. Re-model only the missing step. For faster learners, ask them to test an edge case or explain an alternative; do not add unrelated tasks.</p><h2>Materials and answers</h2><nav>'+resources(n)+'</nav><h2>Alignment</h2><p>GS6 Level 2 objective groups: '+e(', '.join(w['refs']))+'. The final week is a VUB extension.</p>'
 write(folder+'/lesson-plan.html',doc(f'Week {n} lesson plan: '+w['title'],plan))
 # Transcript is populated from final narration beats by the media builder.
 transcript=f'<p>{e(w["summary"])}</p><video {("poster="+chr(34)+photo_scenes.PHOTO_ROOT+photo_scenes.PHOTOS[n][1]+".webp"+chr(34)) if n!=5 else ""} id="transcript-video" tabindex="0" controls preload="metadata" aria-label="Week {n} explainer"><source src="{BASE}/media/week-{n:02}.mp4" type="video/mp4"><track kind="captions" src="{BASE}/media/week-{n:02}.vtt" srclang="en" label="English" default></video>'+chapters(n,"transcript-video")+'<div id="transcript-content">'
 beats=Path(f'video/digital-literacy-2/week-{n:02}/narration/beats.json')
 if beats.exists():
  demo_path=beats.parent.parent/'screen-share-actions.json'
  demos={s['chapter']:s for s in json.loads(demo_path.read_text())} if demo_path.exists() else {}
  for i,b in enumerate(json.loads(beats.read_text())):
   demo=demos.get(i+1)
   guide=('<details class="screen-demo-guide"><summary>Screen demonstration steps</summary><p>This is an original screen simulation with fictional practice data. Menus vary by application. Pause or replay each action before trying it yourself.</p><ol>'+''.join('<li>'+e(a['label'])+'</li>' for a in demo['actions'])+'</ol></details>') if demo else ''
   transcript+=f'<section><h2>{e(b["title"])}</h2><p>{e(b["text"])}</p>{guide}</section>'
 transcript+='</div><div class="actions">'+link(folder+'/presentation.html','Return to lesson','button')+'</div>'
 write(folder+'/video-transcript.html',doc(f'Week {n} explainer and transcript',transcript))
write('index.html',page(C['title'],learning.home(W,link),'course-home'))
dates=['September 28','October 5','October 12','October 19','October 26','November 2']
syll='<p><strong>WV Veterans Upward Bound · IC3 Digital Literacy GS6 Level 2 + Web App Building</strong></p><p><strong>Mondays, September 28–November 2, 2026 · 4:30–6:30 p.m. Eastern Time</strong><br>Six meetings · 12 contact hours · Computer lab instruction</p><p>For veterans who can use a mouse and keyboard, open a browser and manage basic files. Level 1 or equivalent experience is recommended. Ask the instructor for a refresher when needed.</p><h2>What you will be able to do</h2>'+ul([x for w in W for x in w['objectives']])+'<h2>Cohort schedule</h2><table><thead><tr><th>Meeting</th><th>Focus</th><th>Evidence of learning</th></tr></thead><tbody>'
for w,date in zip(W,dates):syll+=f'<tr><td>Week {w["n"]}<br>{date}, 2026<br>4:30–6:30 p.m.</td><td>{e(w["title"])}</td><td>{e(w["summary"])}'+(' Pre-test.' if w['n']==1 else ' Post-test and skills challenge.' if w['n']==5 else ' Prototype and test log.' if w['n']==6 else '')+'</td></tr>'
syll+='</tbody></table><p>The October 12 meeting is included as scheduled. Confirm building access with the program before that meeting.</p><h2>How we will learn</h2><p>Each meeting combines demonstration, a short captioned explainer, guided practice, a break, partner work and a check for understanding. Use fictional examples throughout. The final week supports either an approved AI tool or a supplied starter app with no AI account required.</p><h2>Learning checks</h2><p>The pre-test occurs before instruction in week 1. The parallel post-test follows the GS6 lessons in week 5. Each has 28 questions, four per domain, and produces printable graded results. The week 6 prototype uses a separate 8-point rubric. Scores guide practice; they are not certification results.</p><h2>Materials and access</h2><p>Bring your willingness to practice. A workstation, browser, headphones, word processor, spreadsheet app and plain-text editor support the activities. Captions, transcripts, keyboard navigation, text sizing and print copies are available. No real purchases, private records or paid AI account are needed.</p><h2>Between meetings</h2><p>Optional: repeat one class task with fictional data and note where you need help. Save your worksheets and assessment results before leaving a shared computer.</p><div class="actions">'+link('instructor-guide.html','Six-week lesson plans','button secondary')+'</div>'
write('syllabus.html',doc('Digital Literacy Level 2 syllabus',syll))
index='<p>All six lesson plans and the syllabus derive from the same curriculum source. Each plan totals 120 minutes. Dates appear only on the cohort syllabus.</p><h2>Before the course</h2><p>Test playback, captions, print preview, software access and the lab printer. Provide fictional files and a demonstration account if collaboration features require sign-in. Download the starter HTML for the account-free week 6 path. Keep learner responses out of public repositories.</p><div class="overview-links">'+''.join(link(f'weeks/week-{w["n"]:02}/lesson-plan.html',f'Week {w["n"]}: {w["title"]}') for w in W)+'</div><h2>Assessment kit</h2><div class="overview-links">'+''.join(link(f'assessments/{k}-test{suffix}.html',f'{k.title()}-test {label}') for k in ['pre','post'] for suffix,label in [('', 'browser assessment'),('-printable','paper copy'),('-answer-key','answer key')])+'</div><h2>Practical scoring</h2><p>Record task performance as Independent, With prompt or Needs practice. Use the worksheet answer guides for expected evidence. Keep practical observations separate from the 28-point knowledge score. Use the final worksheet’s 8-point app rubric for the extension.</p><h2>Local data and clearing</h2><p>Slide progress is stored in the browser. Assessment drafts and results stay in the current browser tab’s session storage until cleared or the tab session ends. They are not sent to an instructor automatically. Have learners print or download their results, then select Clear my assessment on shared computers.</p>'+link('sources.html','Research and objective alignment')
write('instructor-guide.html',doc('Instructor guide and lesson plans',index))
sources='<p>This is original VUB teaching material informed by the GS6 Level 2 framework. It uses no certification exam questions or copyrighted software screenshots. The additional app-building week is explicitly outside the GS6 Level 2 assessment score.</p><h2>Primary references</h2><ul><li><a href="https://certiport.pearsonvue.com/Certifications/IC3/Digital-Literacy-Certification/Certify/IC3-Global-Standard-6">Certiport: IC3 Global Standard 6</a> and its Level 2 objective-domain download.</li><li><a href="https://certiport.ccilearning.com/wp-content/uploads/2022/10/IC3_GS6_All_Levels_Exam_Domains.pdf">Certiport-authored objective domains, hosted by CCI Learning</a>, Level 2 pages 4–6. Used for the objective map; this is the accessible reference copy.</li><li><a href="https://support.microsoft.com/en-us/onedrive/restore-a-previous-version-of-a-file-stored-in-onedrive">Microsoft: restore previous OneDrive file versions</a>.</li><li><a href="https://consumer.ftc.gov/articles/how-recognize-avoid-phishing-scams">FTC: recognize and avoid phishing</a>.</li><li><a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API">MDN: browser storage</a>.</li></ul><h2>Teaching coverage</h2><p>Objective numbers below identify the framework groups taught. Lessons, simulations and worksheets provide practice across these groups; the 28-question classroom test samples each of the seven domains equally and is not a full certification readiness prediction.</p><table><thead><tr><th>Week</th><th>Objective groups</th><th>Practice evidence</th></tr></thead><tbody>'+''.join(f'<tr><td>{w["n"]}: {e(w["title"])}</td><td>{e(", ".join(w["refs"]))}</td><td>{e(w["summary"])}</td></tr>' for w in W)+'</tbody></table><h2>Assessment blueprint</h2><table><thead><tr><th>Domain</th><th>Pre / post items</th><th>Teaching week</th></tr></thead><tbody>'+''.join(f'<tr><td>{e(d)}</td><td>4 / 4</td><td>{", ".join(str(x) for x in sorted(set(q["week"] for q in Q["pre"] if q["domain"]==d)))}</td></tr>' for d in dict.fromkeys(q['domain'] for q in Q['pre']))+'</tbody></table><p>The worksheet answer guides include performance evidence for objectives beyond the quiz sample. Re-check vendor instructions when menus change; learning goals and lesson dates remain reusable.</p>'
sources+='<h2>Adult learning and deeper video lessons</h2><p>The chaptered videos connect skills to learner-chosen household and community tasks, model decisions, invite predictions, provide practice with feedback, and ask learners to transfer the routine. Accessibility and learner-controlled replay support different needs without assuming ability from age.</p><ul><li><a href="https://www.cdc.gov/training-development/php/about/develop-training-captivating-and-motivating-adult-learners.html">CDC: engaging adult learners</a>.</li><li><a href="https://www.w3.org/WAI/older-users/">W3C: older users and web accessibility</a>.</li><li><a href="https://support.microsoft.com/en-us/accessibility/word/make-your-word-documents-accessible-to-people-with-disabilities">Microsoft: accessible documents</a>.</li><li><a href="https://support.microsoft.com/en-us/excel/functions/sum-function">Microsoft: SUM and cell ranges</a>.</li><li><a href="https://support.google.com/drive/answer/2494822?hl=en">Google: file-sharing roles</a>.</li><li><a href="https://www.nist.gov/itl/smallbusinesscyber/guidance-topic/phishing">NIST: phishing guidance</a>.</li><li><a href="https://developer.mozilla.org/en-US/docs/Learn_web_development">MDN: learning web development</a>.</li></ul>'
write('sources.html',doc('Sources and curriculum alignment',sources))
for kind,questions in Q.items():
 title=kind.title()+'-test'
 version=3 if kind=='post' else 2
 write(f'assessments/{kind}-test.html',page(title,learning.assessment(kind,link),'assessment',script='assessment.js'))
 paper=f'<p>Assessment version {version} · Fictional practice scenarios</p><p>Name or learner code: ____________________</p><p>Read each situation and choose the one answer that best fits the task. Each correct answer earns one point. Total: 28. This is a classroom assessment, not a certification exam.</p>'
 key=f'<p>Assessment version {version}</p><p>One point per correct answer. Domain totals: four points each. Total: 28. Accept only the keyed choice for the knowledge score; use worksheet rubrics for demonstrated skills.</p>'
 for i,q in enumerate(questions):
  paper+=f'<section class="question"><h2>{i+1}. {e(q["question"])}</h2><ol type="A">'+''.join('<li>☐ '+e(o)+'</li>' for o in q['options'])+'</ol></section>'
  key+=f'<section class="question"><h2>{i+1}. {e(q["question"])}</h2><p><strong>{"ABC"[q["answer"]]}. {e(q["options"][q["answer"]])}</strong></p><p>{e(q["why"])}</p><p>Domain: {e(q["domain"])} · objective {e(q["objective"])} · week {q["week"]}</p></section>'
 write(f'assessments/{kind}-test-printable.html',doc(title+' printable assessment',paper))
 write(f'assessments/{kind}-test-answer-key.html',doc(title+' answer key',key))
# Catalog is the platform discovery source of truth.
p=Path('courses.json'); catalog=json.loads(p.read_text());catalog['courses']=[c for c in catalog['courses'] if c['id']!='digital-literacy-2']
catalog['courses'].append(dict(id='digital-literacy-2',title=C['title'],subtitle='Six practical weeks: IC3 GS6 Level 2 plus building a small web app with AI.',type='weeks',progressKey='dl2',category='Digital Literacy',emphasis='Create, collaborate, build',path='courses/digital-literacy-2/',entry='courses/digital-literacy-2/index.html',preTest='courses/digital-literacy-2/assessments/pre-test.html',postTest='courses/digital-literacy-2/assessments/post-test.html',lessons=[dict(n=w['n'],title=w['title'],topic=w['summary'],path=f'courses/digital-literacy-2/weeks/week-{w["n"]:02}/presentation.html',statusKey=f'dl2:w{w["n"]}') for w in W]))
serialized=json.dumps(catalog,indent=2,ensure_ascii=False)
# Keep the catalog's existing compact lesson-row convention.
import re
serialized=re.sub(r'        \{\n          "n"[\s\S]*?\n        \}',lambda m:'        { '+', '.join(json.dumps(k)+': '+json.dumps(v) for k,v in json.loads(m.group()).items())+' }',serialized)
p.write_text(serialized+'\n')
print('Built',len(list(ROOT.rglob('*.html'))),'course pages')
