"""Approved modern learning-app composition: A navigation + B focus + C topics."""
from html import escape as e
BASE='/courses/digital-literacy-2'
CONTRACT='''<!-- THESIS: A visually rich learning app brings the next real task into view.
OWN-WORLD: VUB navy, gold actions, teal object illustrations, generous humanist type, precise controls.
STORY: Find your place, practice a task, see progress, review and save your results.
FIRST VIEWPORT: Persistent course navigation; substantial illustrated welcome or focus panel; semantic task controls and topic progress.
FORM: User-approved combination of assessment-a, assessment-b and assessment-c; user choice supersedes seed b94465fb.
FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md -->'''
def icon(kind):
 paths={'home':'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10','lessons':'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3ZM12 6v16','pre':'M8 3h8v4H8ZM8 5H5v17h14V5h-3M8 12h8M8 16h5','post':'M4 21V11h4v10M10 21V7h4v14M16 21V3h4v18','resources':'M4 4h6l2 3h8v14H4Z','arrow':'M4 12h16M14 6l6 6-6 6'}
 return f'<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="{paths[kind]}"/></svg>'
def rail():
 items=[('home','index.html','Course overview'),('lessons','index.html#course-weeks','Lessons'),('pre','assessments/pre-test.html','Pre-test'),('post','assessments/post-test.html','Post-test'),('resources','syllabus.html','Syllabus')]
 return '<aside class="app-rail" aria-label="Course workspace"><button class="app-menu" type="button" aria-expanded="false" aria-controls="course-links">Course navigation</button><p class="rail-title">Your learning<br>workspace</p><nav id="course-links" aria-label="Course">'+''.join(f'<a data-app-route href="{BASE}/{p}">{icon(k)}<span>{label}</span></a>' for k,p,label in items)+'<a href="'+BASE+'/instructor-guide.html">'+icon('resources')+'<span>Instructor materials</span></a></nav><div class="rail-bottom"><p>One useful skill.<br>One step forward.</p><div data-text-dock></div></div></aside>'
def frame(body):return '<div class="app-frame">'+rail()+'<div class="app-content">'+body+'</div></div>'
def home(weeks,link):
 rows=[]
 for w in weeks:
  n=w['n'];path=f'weeks/week-{n:02}'
  rows.append(f'<article class="learning-week" data-course-week="{n}"><div class="week-art week-art-{n}"><span>Week {n}</span><div class="week-symbol" aria-hidden="true">{icon(["home","resources","lessons","pre","post","arrow"][n-1])}</div></div><div class="week-detail"><h3>{e(w["title"])}</h3><p>{e(w["summary"])}</p><p class="course-status" data-week-status="{n}">Ready to begin</p><div class="actions">'+link(path+'/presentation.html',f'Open week {n}','button')+link(path+'/worksheet.html','Worksheet')+'</div></div></article>')
 return '''<main class="learning-home" id="main"><section class="learning-hero"><div class="hero-copy"><h1>Build confidence.<br>Make it practical.</h1><p>Digital Literacy Level 2</p><p class="hero-description">Six practical weeks to create, collaborate, stay safe—and build something of your own.</p><div class="actions">'''+link('weeks/week-01/presentation.html','Begin week 1','button gold continue-course')+'''</div></div></section><section class="course-pulse" aria-label="Your course progress"><div><h2>Your next step</h2><p data-continue-caption>Start with a learning check, then explore week 1.</p></div><div class="course-progress-detail"><span data-course-count>0 of 6 lessons viewed to the end</span><progress data-course-progress max="6" value="0" aria-label="Lessons viewed to the end"></progress><small>Progress stays in this browser.</small></div></section><div class="home-lower"><section id="course-weeks"><div class="section-heading"><h2>Your six-week path</h2><p>Learn it. Try it. Make it yours.</p></div><div class="learning-weeks">'''+''.join(rows)+'''</div></section><aside class="learning-tools"><section class="check-in"><h2>See your progress.</h2><p>Begin with the pre-test. Return after week 5 to see what you have learned.</p>'''+link('assessments/pre-test.html','Take the pre-test','button gold')+link('assessments/post-test.html','Take the post-test','button secondary')+'''</section><section class="learning-support"><h2>Make this your space.</h2><p>Enlarge the text, turn on captions, or use a printed worksheet. Take the time you need.</p>'''+link('syllabus.html','View syllabus')+link('sources.html','Sources and course alignment')+'''<p class="small">Classroom learning checks guide practice. This course does not administer or award IC3 certification.</p></section></aside></div></main>'''
def assessment(kind,link):
 title='Pre-test' if kind=='pre' else 'Post-test'
 headline='Start where<br>you are.' if kind=='pre' else 'See how far<br>you have come.'
 copy='This check helps you see what to practice.' if kind=='pre' else 'Use what you have learned. Then review your results.'
 profile='<label for="learner-name">Learner name or code (optional)</label><input id="learner-name" name="learner" maxlength="80" autocomplete="off">'
 if kind=='post':profile+='<label for="pre-score">Your saved pre-test score out of 28 (optional)</label><input id="pre-score" name="preScore" type="number" min="0" max="28" step="1"><p>Enter your own saved result, not a percentage. Leave blank if unavailable.</p>'
 return f'''<main class="learning-assessment" id="main"><div class="assessment-heading"><h1>{title}</h1><p>Digital Literacy Level 2 · 28 questions · 7 topics</p></div><nav id="assessment-topics" class="assessment-topics" aria-label="Assessment topics"></nav><div class="assessment-layout"><aside class="assessment-story"><div><h2>{headline}</h2><p>{copy}</p></div><p class="story-note">About 25 minutes · No countdown</p></aside><div class="assessment-task"><div id="assessment-error" role="alert"></div><form id="assessment-form" class="assessment-form questionnaire" data-kind="{kind}" novalidate><div class="assessment-meter"><span id="question-position">Loading your learning check…</span><span id="answer-count" role="status">0 of 28 answered</span><progress id="assessment-progress" value="0" max="28" aria-label="Questions answered"></progress></div><details class="learner-details"><summary>Add your name or saved score (optional)</summary>{profile}</details><div id="questions"><p>Loading questions…</p></div><div class="question-navigation"><button type="button" id="question-previous" class="secondary" disabled>Previous question</button><button type="button" id="question-next" disabled>Next question {icon('arrow')}</button></div><div class="assessment-actions"><button type="button" class="text-action" id="review-questions" disabled>Review all questions</button><button type="submit" id="grade" disabled>Grade my assessment</button></div><div class="assessment-footnote"><p>Answers stay in this browser tab. They are not submitted to a server.</p><details><summary>About this learning check</summary><p>Choose one answer per question. Four questions cover each GS6 domain. This is a classroom learning check, not an IC3 certification exam. Print or download your results, then clear them on a shared computer.</p><p>Topics: technology basics; digital citizenship; information management; content creation; communication; collaboration; safety and security.</p></details><button type="button" class="text-action" id="clear-assessment">Clear my assessment</button>{link(f'assessments/{kind}-test-printable.html','Printable paper assessment')}</div></form><section id="results" class="results" hidden aria-labelledby="results-title"></section><noscript><p>JavaScript is needed for automatic grading. Use the printable assessment with your instructor.</p></noscript></div></div></main>'''
