"""Prepare performance direction without changing any learner-facing words.

Generation is a separate, explicit ElevenLabs MCP action. Existing takes are
never regenerated by this script. Creative V3 delivery is checked by ASR before
the batch is imported; performance tags never become caption text.
"""
import json
import re
from pathlib import Path

ROOT = Path('video/digital-literacy-2')
LOCAL = Path.home() / 'Desktop/vub-expressive-narration'
PROFILE = dict(model='eleven_v3', voice='iKrofGyA12WC0e6AhZ8B',
               voiceName='Britt - Mild Appalachian Male Voice', speed=0.95,
               stability=0, similarityBoost=0.8, style=0,
               useSpeakerBoost=False, language='en', outputFormat='mp3_44100_128')

# Direct the teaching moment: approachable setup, curiosity, a clear result,
# then encouragement. Security chapters stay reassuring rather than excited.
# Keys are one-based chapters; each cue is an exact authored sentence prefix.
DIRECTION = {
  1: [
    ('warmly', 'We will apply', 'enthusiastically', 'Our goal is', 'encouraging'),
    ('curious', 'Watch the page', 'pleased', 'Pause the video', 'encouraging'),
    ('thoughtful', 'Which would you', 'curious', 'Browser zoom,', 'confident'),
    ('warmly', 'A computer can', 'interested', 'Change one setting', 'encouraging'),
    ('interested', 'Think of a workbench', 'warmly', 'Match the labels', 'encouraging'),
    ('warmly', 'Only then print more.', 'pleased', 'If the printer', 'thoughtful'),
    ('warmly', 'Change the view', 'encouraging', 'Reopening it confirms', 'pleased'),
    ('thoughtful', 'Pause and decide:', 'curious', 'No. Start with', 'confident'),
    ('interested', 'Describe the task', 'encouraging', 'That is useful evidence', 'pleased'),
    ('encouraging', 'If the result is', 'reassuring', 'It is choosing', 'enthusiastically'),
  ],
  2: [
    ('warmly', 'You can use a different', 'encouraging', 'A useful search ends', 'confident'),
    ('interested', 'If there are no useful', 'reassuring', 'Pause and write', 'encouraging'),
    ('curious', 'Compare two pages', 'interested', 'Do not count votes', 'confident'),
    ('warmly', 'A note saying', 'curious', 'This is the digital', 'warmly'),
    ('warmly', 'That distinction matters:', 'confident', 'Pause, complete', 'encouraging'),
    ('warmly', 'Reopen the file', 'encouraging', 'That simple test', 'pleased'),
    ('interested', 'Pause and choose', 'curious', 'Viewer is the appropriate', 'confident'),
    ('interested', 'That is why', 'confident', 'Use the fictional copy', 'encouraging'),
    ('thoughtful', 'After extracting', 'encouraging', 'Choose the tool', 'confident'),
    ('encouraging', 'Then explain how', 'curious', 'For your next', 'enthusiastically'),
  ],
  3: [
    ('warmly', 'What helped you', 'curious', 'We will apply', 'enthusiastically'),
    ('warmly', 'Does it still', 'curious', 'That is a useful', 'pleased'),
    ('warmly', 'Practice on a copy', 'reassuring', 'Pause and propose', 'encouraging'),
    ('interested', 'B2 means', 'confident', 'Before calculating', 'encouraging'),
    ('warmly', 'Now change paper', 'curious', 'The total should', 'excited'),
    ('interested', 'If a chart looks', 'curious', 'Keep the table', 'encouraging'),
    ('enthusiastically', 'Those actions solve', 'confident', 'Preserve the original', 'encouraging'),
    ('interested', 'Watch both sides', 'curious', 'The goal is for', 'encouraging'),
    ('warmly', 'Reopen the exported', 'encouraging', 'Use original or', 'confident'),
    ('encouraging', 'Can they identify', 'curious', 'This is useful evidence', 'pleased'),
  ],
  4: [
    ('warmly', None, None, None, None),
    ('interested', None, None, None, None),
    ('warmly', 'Could they act', 'curious', 'In this course,', 'encouraging'),
    ('thoughtful', 'Pause and review', 'encouraging', 'Clear communication includes', 'confident'),
    ('curious', 'Instead, agree', 'encouraging', 'Neither is automatically', 'thoughtful'),
    ('interested', 'The writer can', 'warmly', 'Pause and write', 'encouraging'),
    ('warmly', 'If the connection fails', 'reassuring', 'Preparation reduces', 'pleased'),
    ('warmly', 'You already use', 'encouraging', 'Bring that same habit', 'confident'),
    ('thoughtful', 'Our practice ends', 'reassuring', 'Pause and name', 'curious'),
    ('encouraging', 'Judge success', 'pleased', 'For a group task', 'warmly'),
  ],
  5: [
    ('warmly', 'Those habits are valuable', 'encouraging', 'You do not need', 'reassuring'),
    ('warmly', 'People differ', 'thoughtful', 'Pause and choose', 'encouraging'),
    ('thoughtful', 'The urgency is', 'confident', 'That helps you', 'reassuring'),
    ('confident', 'Pause and choose', 'curious', 'The known route', 'reassuring'),
    ('curious', 'Inspect what the feature', 'confident', 'Pause and explain', 'encouraging'),
    ('thoughtful', 'Do not plug', 'confident', 'This is not about', 'reassuring'),
    ('warmly', 'Pause and compare', 'curious', 'Explain why', 'encouraging'),
    ('warmly', 'Choose notification settings', 'encouraging', 'You do not have', 'reassuring'),
    ('interested', 'Pause the video', 'encouraging', 'If you disagree', 'warmly'),
    ('encouraging', 'A classroom score', 'reassuring', 'Confidence grows', 'pleased'),
  ],
  6: [
    ('warmly', 'We will turn', 'enthusiastically', 'You do not need', 'reassuring'),
    ('interested', 'Our one-file practice', 'thoughtful', 'Start by describing', 'encouraging'),
    ('interested', 'Think of a familiar', 'warmly', 'Open the supplied', 'encouraging'),
    ('confident', 'Pause and write', 'encouraging', 'Ask a partner', 'curious'),
    ('warmly', 'Do not put passwords', 'confident', 'A longer prompt', 'thoughtful'),
    ('encouraging', 'If no AI account', 'reassuring', 'The goal is', 'pleased'),
    ('curious', 'Clear the field', 'encouraging', 'The evidence is', 'confident'),
    ('encouraging', 'Can you see', 'curious', 'Test persistence', 'confident'),
    ('curious', 'If the new version', 'reassuring', 'Pause and make', 'encouraging'),
    ('enthusiastically', 'A local fictional prototype', 'pleased', 'Carry forward', 'encouraging'),
  ],
}

jobs = []
for week in range(1, 7):
  folder = ROOT / f'week-{week:02}' / 'narration'
  for index, beat in enumerate(json.loads((folder / 'beats.json').read_text())):
    opening, first, first_tag, second, second_tag = DIRECTION[week][index]
    prompt = '[' + opening + '] ' + beat['text']
    for phrase, tag in [(first, first_tag), (second, second_tag)]:
      if phrase:
        assert prompt.count(phrase) == 1, (week, beat['id'], phrase)
        prompt = prompt.replace(phrase, f'[{tag}] {phrase}', 1)
    # A pause before independent practice gives the learner a clear handoff.
    prompt = re.sub(r'(?<!\w)(Pause (?:the video|and |,))', r'[short pause] \1', prompt, count=1)
    local = LOCAL / folder.parent.name / beat['id']
    approved = ROOT / 'elevenlabs-britt-v3-expressive' / folder.parent.name / beat['id']
    local.mkdir(parents=True, exist_ok=True)
    saved = local / 'prompt.txt'
    if saved.exists():
      # The initial formula sample is an intentionally more directed performance.
      prompt = saved.read_text().strip()
    else:
      if (approved / 'prompt.txt').exists():
        prompt = (approved / 'prompt.txt').read_text().strip()
      saved.write_text(prompt + '\n')
    settings = local / 'generation-settings.json'
    if not settings.exists():
      previous = json.loads((approved / 'receipt.json').read_text()) if (approved / 'receipt.json').exists() else PROFILE
      settings.write_text(json.dumps({key: previous[key] for key in PROFILE}, indent=2) + '\n')
    assert ' '.join(re.sub(r'\[[^]]+\]', '', prompt).split()) == ' '.join(beat['text'].split())
    jobs.append(dict(week=week, chapter=index+1, title=beat['title'], text=prompt))

destination = ROOT / 'elevenlabs-britt-v3-expressive'
destination.mkdir(exist_ok=True)
(destination / 'profile.json').write_text(json.dumps(PROFILE, indent=2) + '\n')
(destination / 'performance-plan.json').write_text(json.dumps(jobs, indent=2) + '\n')
print(f'Prepared {len(jobs)} directed chapters; original spoken words preserved.')
