"""Original, fictional teaching interfaces shared by the course's visual workshop."""
from html import escape as esc

def buttons(items,action):
 return '<div class="work-controls">'+''.join(f'<button type="button" data-action="{action}" data-value="{esc(v)}" aria-pressed="false">{esc(t)}</button>' for v,t in items)+'</div>'
def window(title,body):
 return f'<div class="work-window"><div class="window-bar"><svg viewBox="0 0 40 16" width="40" height="16" aria-hidden="true"><circle cx="6" cy="8" r="4"/><circle cx="20" cy="8" r="4"/><circle cx="34" cy="8" r="4"/></svg><span>{title}</span></div><div class="window-content">{body}</div></div>'
def wrap(kind,title,body,hint):
 return f'<div class="workshop" data-workshop="{kind}"><div class="work-heading"><h3>{title}</h3><span class="simulation-label">Practice simulation</span></div>{body}<p class="work-outcome" role="status">{hint}</p></div>'

def workshop(kind):
 if kind=='zoom':
  return wrap(kind,'Make the page work for you',window('Community learning · fictional webpage','<div class="browser-tools"><span>Page zoom</span>'+buttons([('100','100%'),('125','125%'),('150','150%')],'zoom')+'</div><div class="zoom-page"><h4>Computer help, at your pace.</h4><p>Bring a question. Practice one useful task with a partner.</p><span class="example-link">Explore learning resources</span></div>'),'Select a zoom level. Only the practice webpage changes; the browser controls stay the same size.')
 if kind=='sound':
  return wrap(kind,'Follow the sound',window('Sound settings','<div class="signal-path"><div class="signal-source">Computer audio</div><svg viewBox="0 0 100 24" aria-hidden="true"><path d="M2 12h90m-12-9 12 9-12 9"/></svg><div data-output>Headphones</div></div>'+buttons([('headphones','Headphones'),('speakers','Speakers')],'output')+'<div class="work-controls"><button type="button" data-action="mute" aria-pressed="false">Mute: off</button><button type="button" data-action="sound-test">Run visual sound test</button></div><div class="sound-meter" aria-label="Sound test indicator"><i></i><i></i><i></i><i></i><i></i><i></i></div>'),'Select an output, then test. This visual simulation does not play sound or change your device.')
 if kind=='calendar':
  month='<div class="month-map">'+''.join('<strong>'+d+'</strong>' for d in ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])+''.join(f'<div class="month-cell"><span>{i}</span>'+({1:'<b>Computer practice</b>',2:'<b>Library visit</b>',3:'<b>Partner review</b>'}.get(i,''))+'</div>' for i in range(1,29))+'</div>'
  return wrap(kind,'Same plans. A different view.',buttons([('week','Week'),('day','Day'),('month','Month'),('list','List')],'calendar')+window('Practice calendar','<div class="calendar-surface" data-view="week" tabindex="0" role="region" aria-label="Practice calendar. Use left and right arrow keys to scroll."><div class="calendar-day"><strong>Monday</strong><div class="calendar-event">Computer practice<span>3:00–4:00</span></div></div><div class="calendar-day"><strong>Tuesday</strong><div class="calendar-event gold-event">Library visit<span>10:00–11:00</span></div></div><div class="calendar-day"><strong>Wednesday</strong><div class="calendar-event">Partner review<span>2:00–2:30</span></div></div>'+month+'</div>'),'Select a view. The events stay the same; the arrangement changes. Day view shows Monday.')
 if kind=='privacy':
  return wrap(kind,'See what your partner sees',buttons([('busy','Free / busy'),('details','Event details')],'privacy')+'<div class="comparison"><div><h4>Your calendar</h4><div class="calendar-event">Practice appointment<span>2:00–3:00 · Room A</span></div></div><div><h4>Partner’s view</h4><div class="calendar-event gold-event" data-shared-event>Busy<span>2:00–3:00</span></div></div></div>','Free / busy shares availability without the title or location. This changes only the fictional preview.')
 if kind=='sync':
  return wrap(kind,'Watch a deletion travel',window('One synced file · two locations','<div class="sync-map"><div><h4>This computer</h4><div class="file-object" data-local-file>Resource guide.docx</div></div><div class="sync-arrow" aria-hidden="true"><svg width="50" height="32" viewBox="0 0 50 32"><path d="M3 10h40m-8-7 8 7-8 7M47 23H7m8-7-8 7 8 7" fill="none" stroke="currentColor" stroke-width="3"/></svg></div><div><h4>Cloud account</h4><div class="file-object" data-cloud-file>Resource guide.docx</div></div></div><div class="backup-copy"><strong>Separate backup</strong><span>Resource guide.docx · earlier saved copy</span></div>')+buttons([('delete','Delete synced file'),('restore','Restore from backup'),('reset','Reset example')],'sync'),'A separate backup is outside this sync relationship. Try deleting the synced file.')
 if kind=='source':
  return wrap(kind,'Look beyond the headline',window('Fictional search result','<div class="source-result"><span class="example-link">Community computer help</span><p>Drop-in help for basic computer tasks.</p><dl><dt>Author</dt><dd>Community learning team</dd><dt>Purpose</dt><dd>Describe a local service</dd><dt>Evidence</dt><dd>Contact details and service policy</dd></dl></div>')+buttons([('author','Who wrote it?'),('date','Is it current?'),('purpose','Why publish it?')],'source'),'Select a check to see what it can—and cannot—tell you.')
 if kind=='document':
  return wrap(kind,'Structure changes how a document works',buttons([('plain','Plain paragraphs'),('structured','Heading + steps')],'document')+window('Fictional resource handout','<div class="document-page" data-document><div class="document-title">Find computer help</div><div class="document-line">Choose one task you want to practice.</div><div class="document-line">Bring your question to the learning desk.</div><div class="document-line">Ask how to repeat the task at home.</div></div>'),'Compare the two versions. A heading and ordered steps make the reading path explicit.')
 if kind=='sheet':
  return wrap(kind,'Make the formula prove itself',window('Supplies · fictional workbook','<div class="formula-bar"><span>B5</span><code>=SUM(B2:B4)</code></div><table class="demo-sheet"><thead><tr><th aria-label="Row number"></th><th scope="col">A</th><th scope="col">B</th></tr></thead><tbody><tr><th scope="row">1</th><td>Item</td><td>Cost</td></tr><tr><th scope="row">2</th><td>Paper</td><td data-paper class="formula-cell">$12</td></tr><tr><th scope="row">3</th><td>Folders</td><td class="formula-cell">$8</td></tr><tr><th scope="row">4</th><td>Pens</td><td class="formula-cell">$5</td></tr><tr class="sum-row"><th scope="row">5</th><td>Total</td><td data-sum>$25</td></tr></tbody></table>')+buttons([('15','Change paper to $15'),('12','Restore paper to $12')],'sheet'),'Predict the new total before you change the value. A working formula recalculates.')
 if kind=='export':
  return wrap(kind,'Choose what survives the export',buttons([('doc','Editable document'),('pdf','PDF'),('csv','CSV')],'export')+window('Export preview','<div class="export-preview"><div class="file-extension" data-extension>DOCX</div><div><h4 data-export-title>Keep revising together</h4><p data-export-copy>Preserve editable text and document structure in a compatible app.</p></div></div>'),'Choose a format, then explain what the next person needs to do.')
 if kind=='feedback':
  return wrap(kind,'Turn a reaction into useful feedback',window('Shared handout · fictional comments','<div class="review-document"><h4>How to get computer help</h4><ol><li>Choose a task.</li><li>Visit the learning desk.</li></ol></div><div class="comment-thread"><span class="avatar" aria-hidden="true">A</span><div><strong>Alex · Reviewer</strong><p data-comment>This is confusing.</p></div></div>')+buttons([('vague','Vague reaction'),('specific','Specific suggestion'),('resolved','Writer responds')],'feedback'),'A useful comment names the location, the change and the reason.')
 if kind=='meeting':
  return wrap(kind,'Practice the meeting controls',window('Practice meeting · no camera or microphone access','<div class="meeting-stage"><div><span class="participant-mark">You</span><span data-mic-state>Microphone muted</span></div><div><span class="participant-mark">Host</span><span>Explaining the task</span></div></div><div class="work-controls"><button type="button" data-action="meeting-mic" aria-pressed="false">Unmute microphone</button><button type="button" data-action="hand" aria-pressed="false">Raise hand</button></div>'),'These controls affect only the model. Raise your hand to show you want to speak.')
 if kind=='phishing':
  return wrap(kind,'Inspect before you act',window('Fictional inbox · training example','<div class="message-preview"><strong>Subject:</strong> '+buttons([('urgency','Act now: account will close')],'inspect')+'<strong>From:</strong> '+buttons([('sender','support@account-check.example')],'inspect')+'<p>Verify your password immediately.</p>'+buttons([('link','Inspect the “Verify account” link')],'inspect')+'</div>')+buttons([('verify','Choose an independent check')],'inspect'),'Inspect the subject, sender and link. No links here open a website or send information.')
 if kind=='access':
  return wrap(kind,'Does this permission fit the task?',window('Fictional app request','<div class="permission-request"><svg viewBox="0 0 80 64" aria-hidden="true"><rect x="8" y="14" width="42" height="36" rx="8"/><path d="m50 24 20-10v36L50 40z"/></svg><h4>A text-only resource page wants camera access.</h4></div>'+buttons([('allow','Allow camera'),('deny','Deny camera')],'access')),'Decide based on the task. This simulation never requests real camera access.')
 if kind=='encrypt':
  return wrap(kind,'Editing and reading are different permissions',buttons([('plain','Original data'),('readonly','Read-only'),('encrypted','Encrypted')],'encrypt')+window('Fictional file protection','<div class="protected-file"><h4 data-protection>Original file</h4><pre data-file-text>Practice notes\nResource desk · Room A</pre><p data-protection-note>Readable and editable.</p></div>'),'Compare what someone can read with what they can change. The encrypted text is illustrative, not a real encryption tool.')
 if kind=='parts':
  return wrap(kind,'Three layers. One working page.',buttons([('html','HTML'),('css','CSS'),('js','JavaScript')],'parts')+'<div class="code-workspace"><pre data-code>&lt;h1&gt;Find a resource&lt;/h1&gt;\n&lt;input aria-label="Search"&gt;</pre><div class="mini-app"><h4>Find a resource</h4><span class="mock-search">Search resources</span><div class="result-row">Learning desk</div><div class="result-row">Community library</div></div></div>','HTML supplies the content and structure. Select a layer to see its job.')
 if kind=='app':
  return wrap(kind,'Try the app’s edge cases',window('Fictional resource finder','<label>Search the practice resources<input data-resource-search type="search" placeholder="Try library or zzz" autocomplete="off"></label><div class="resource-results" aria-live="polite"><div class="result-row">Community library · Learning</div><div class="result-row">Computer help desk · Learning</div><div class="result-row">Neighborhood center · Community</div></div>')+buttons([('library','Test a match'),('zzz','Test no match'),('','Reset search')],'app'),'Try an uppercase search too. Matching should not depend on letter case.')
 if kind=='prompt':
  return wrap(kind,'Turn an idea into clear instructions','<label>Your fictional app’s task<input data-prompt-task value="Find a community resource" maxlength="120"></label><div class="prompt-checks"><label><input type="checkbox" data-requirement="Include labeled search and a category filter." checked> Search and filter</label><label><input type="checkbox" data-requirement="Support keyboard access and visible focus." checked> Keyboard access</label><label><input type="checkbox" data-requirement="Explain an empty result and test mixed-case search." checked> Test edge cases</label></div><button type="button" data-action="prompt">Build the practice prompt</button><pre class="prompt-preview" data-prompt-output>Choose requirements, then build your prompt.</pre>','Use fictional records, keep secrets out of browser code, and test the result yourself. Nothing is sent to an AI service.')
 return ''

MAP={1:{5:'zoom',6:'zoom',7:'sound',14:'privacy',15:'calendar'},2:{5:'source',13:'sync',18:'sync'},3:{3:'document',10:'sheet',17:'export'},4:{4:'feedback',12:'feedback',14:'meeting'},5:{8:'phishing',10:'encrypt',13:'access'},6:{5:'parts',7:'prompt',9:'app',17:'app'}}
def for_slide(week,slide): return workshop(MAP.get(week,{}).get(slide,''))
